### ISSUE TITLE
Setting functions:config with .runtimeconfig.json also deletes its contents and prevents emulator deployment

### ISSUE THREAD

**Issue by DaveMitten** [firebase/firebase-functions#1005]
### [REQUIRED] Version info

**node:**v14.17.6

**firebase-functions:**^3.16.0

**firebase-tools:**^9.22.0

**firebase-admin:** 9.23.0

### [REQUIRED] Test case

Run the Command below in "Steps to reproduce"

### [REQUIRED] Steps to reproduce

Run npm run dev OR  tsc && ts-node-dev --poll | firebase functions:config:get > .runtimeconfig.json | firebase emulators:start --import=./firestore_emulator_data

Specifically:
 firebase functions:config:get > .runtimeconfig.json

### [REQUIRED] Expected behavior

Builds project and serves locally the emulations with correct configs.

### [REQUIRED] Actual behavior

Deletes contents of  .runtimeconfig.json. Fails to successfully deploy emulation locally. Claims config env keys don't exist, which, if it does not set or get them would make sense.

### Were you able to successfully deploy your functions?
No.

  functions: Watching "/Users/<blah>/<blah>/<blah>/<blah>/functions" for Cloud Functions...
⚠  It looks like you're trying to access functions.config().stripe but there is no value there. You can learn more about setting up config here: https://firebase.google.com/docs/functions/local-emulator
⚠  TypeError: Cannot read property 'live' of undefined
    at Object.<anonymous> (/Users/<blah>/<blah>/<blah>/<blah>/functions/lib/<blah>/<blah>.js:53:59)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/<blah>/<blah>/<blah>/<blah>/functions/lib/<blah>/<blah>.js:33:19)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
⚠  We were unable to load your functions code. (see above)
   - It appears your code is written in Typescript, which must be compiled before emulation.
   - You may be able to run "npm run build" in your functions directory to resolve this.

**Comment by taeold** [comment]
Hi @DaveMitten - thanks for filing the issue.

Here are few suggestions:

* `firebase functions:config:get` can be flaky. Can you inspect the logs to see if the command was successful?
* `firebase functions:config:get` can be slow. Can you make sure that the command completes before running the emulator? e.g. `irebase functions:config:get > .runtimeconfig.json && firebase emulators:start --import=./firestore_emulator_data` instead?
