### ISSUE TITLE
TypeError: entry.toJSON is not a function

### ISSUE THREAD

**Issue by deepak786** [firebase/firebase-functions#1102]
Getting the below error in the trigger `functions.auth.user().onDelete`

```
TypeError: entry.toJSON is not a function
   at /workspace/node_modules/firebase-functions/lib/common/providers/identity.js:113:70
   at Array.map (<anonymous>) 
   at Object.record.toJSON (/workspace/node_modules/firebase-functions/lib/common/providers/identity.js:113:49)
   at JSON.stringify (<anonymous>) 
   at onUserDeleted (/workspace/user_deleted/index.js:13:59) 
   at cloudFunction (/workspace/node_modules/firebase-functions/lib/cloud-functions.js:135:23)
   at /layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/function_wrappers.js:144:25
   at processTicksAndRejections (internal/process/task_queues.js:97:5) 
```

cloud function trigger
```
exports.goodByeUser = functions.auth.user().onDelete((user) => {
  console.log(`deleting data of user ${JSON.stringify(user)}`); // this JSON.stringify gives the error
});
```

package.json
```
{
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "scripts": {
    "lint": "eslint .",
    "serve": "firebase serve --only functions",
    "shell": "firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "dependencies": {
    "aws-sdk": "^2.658.0",
    "axios": "^0.21.1",
    "body-parser": "^1.19.0",
    "cors": "^2.8.5",
    "currencyformatter.js": "^2.2.0",
    "express": "^4.17.1",
    "firebase-admin": "^10.2.0",
    "firebase-functions": "^3.21.0",
    "jsonexport": "^3.0.1",
    "moment": "^2.24.0",
    "nanoid": "^3.0.2",
    "request": "^2.88.0"
  },
  "devDependencies": {
    "eslint": "^5.12.0",
    "eslint-plugin-promise": "^4.0.1"
  },
  "private": true,
  "engines": {
    "node": "12"
  }
}

```

This was working fine with the below configuration:
```
{
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "scripts": {
    "lint": "eslint .",
    "serve": "firebase serve --only functions",
    "shell": "firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "dependencies": {
    "aws-sdk": "^2.658.0",
    "axios": "^0.21.1",
    "body-parser": "^1.19.0",
    "cors": "^2.8.5",
    "currencyformatter.js": "^2.2.0",
    "express": "^4.17.1",
    "firebase-admin": "^9.11.0",
    "firebase-functions": "^3.14.1",
    "jsonexport": "^3.0.1",
    "moment": "^2.24.0",
    "nanoid": "^3.0.2",
    "request": "^2.88.0"
  },
  "devDependencies": {
    "eslint": "^5.12.0",
    "eslint-plugin-promise": "^4.0.1"
  },
  "private": true,
  "engines": {
    "node": "10"
  }
}

```

I updated the `firebase-admin` and `firebase-functions` dependencies and updated the Node environment to 12.

**Comment by colerogers** [comment]
Apologies, it seems when we upgraded a module from `lodash` we didn't re-implement `toJSON` fully. Thanks for catching this!

**Comment by sandijs-private** [comment]
This problem actually is blocker level problem, because some old nodejs packages got security issues, and you cannot use older libraries versions as you cannot deploy such code to google serverless cloud.
With old libraries you cannot publish, and the new ones do not function.
I hope I am right about why old libraries versions did not get published.

**Comment by deepak786** [comment]
@colerogers Now I have to wait for the new release, right?

**Comment by colerogers** [comment]
@deepak786 That's correct, we'll work on cutting a release soon.

**Comment by deepak786** [comment]
Thank You @colerogers

**Comment by avi-l** [comment]
Is there a workaround? What version do I need to install in order to make this function work?
```
exports.newUser = functions.auth.user().onCreate((user) => {
  return db
      .collection("user")
      .doc(user.uid)
      .create(JSON.parse(JSON.stringify(user)));
});
```

**Comment by avi-l** [comment]
Great! It's working now, thank you. and thanks @deepak786 for reporting the issue.

**Comment by puf** [comment]
Also reported on https://stackoverflow.com/q/72185429
