### ISSUE TITLE
Blocking: `firebase-tools` Complains About Latest Version of `firebase-functions`

### ISSUE THREAD

**Issue by Swivelgames** [firebase/firebase-functions#114]
After yesterday's deployment tools that broke engines that didn't satisfy "~0.10.12", I updated all versions of `firebase-*` related packages (global and local). I'm no longer able to use the tools:

```
=== Serving from '/Users/****/Projects/node/****'...

i  functions: Preparing to emulate functions.
⚠  functions: Failed to load functions source code. Ensure that you have the latest SDK by running npm i --save firebase-functions inside the functions directory.
⚠  functions: Error from emulator. Error
    at Error.FirebaseError (/****/node_modules/firebase-tools/lib/error.js:11:17)
    at ChildProcess.<anonymous> (/****/node_modules/firebase-tools/lib/parseTriggers.js:24:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:787:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

Versions:
```
$ node --version
v6.11.4

$ cat package.json | grep firebase
    "firebase-admin": "^5.4.1",
    "firebase-functions": "^0.7.0",

$ firebase --version
3.13.0

$ cat yarn.lock | grep firebase
firebase-admin@^5.4.1:
  resolved "https://registry.yarnpkg.com/firebase-admin/-/firebase-admin-5.4.1.tgz#6a930c5ed3ffceb7772394a50ba60497ec5090f6"
firebase-functions@^0.7.0:
  resolved "https://registry.yarnpkg.com/firebase-functions/-/firebase-functions-0.7.0.tgz#a3a7041601c8500d9ab81bcf92f6a391fd87028e"
```

**Comment by laurenzlong** [comment]
@Swivelgames Do you have a Firestore function? And are you able to deploy your project properly still?

**Comment by Swivelgames** [comment]
@laurenzlong Firestore? Negative. Just firebase function, which is the project I'm working in right now that doesn't seem to be working anymore.

*Please note that each attempt is being done on a known working revision that was fully functional prior to the updates published yesterday.*

# [Failed Attempt] Local With Update All Dependencies

_(Please note this was attempted with both `yarn` and `npm` with the same result)_

```
$ yarn global remove firebase-tools
yarn global v1.0.1
...(truncated)...
success Uninstalled packages.

$ yarn remove firebase-admin firebase-functions
yarn remove v1.0.1
...(truncated)...
success Uninstalled packages.

$ yarn add firebase-admin@latest firebase-functions@latest
yarn add v1.0.1
...(truncated)...
success Saved 205 new dependencies.
...(truncated)...

$ yarn global add firebase-tools
yarn global v1.0.1
...(truncated)...
success Installed "firebase-tools@3.13.0" with binaries:
      - firebase

$ cd ..

$ yarn start
yarn start v1.0.1
...(truncated)...

=== Serving from '/******/Projects/node/******'...

i  functions: Preparing to emulate functions.
⚠  functions: Failed to load functions source code. Ensure that you have the latest SDK by running npm i --save firebase-functions inside the functions directory.
⚠  functions: Error from emulator. Error
    at Error.FirebaseError (/******/.config/yarn/global/node_modules/firebase-tools/lib/error.js:11:17)
    at ChildProcess.<anonymous> (/******/.config/yarn/global/node_modules/firebase-tools/lib/parseTriggers.js:24:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:787:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
^C Shutting down...


$ cat package.json yarn.lock src/package.json src/yarn.lock | grep fire
    "deploy": "firebase deploy",
    "start": "yarn run build && firebase serve --only functions",
    "firebase-admin": "^5.4.1",
    "firebase-functions": "^0.7.0",
"@google-cloud/firestore@~0.8.1":
  resolved "https://registry.yarnpkg.com/@google-cloud/firestore/-/firestore-0.8.1.tgz#f741986ec57e64c763090db6da9fea3acb9dfe0e"
firebase-admin@^5.4.1:
  resolved "https://registry.yarnpkg.com/firebase-admin/-/firebase-admin-5.4.1.tgz#6a930c5ed3ffceb7772394a50ba60497ec5090f6"
    "@google-cloud/firestore" "~0.8.1"
firebase-functions@^0.7.0:
  resolved "https://registry.yarnpkg.com/firebase-functions/-/firebase-functions-0.7.0.tgz#a3a7041601c8500d9ab81bcf92f6a391fd87028e"
```

# [Failed Attempt] Deploy: Known Working Project Revision

```
$ yarn run deploy
yarn run v1.0.1
...(truncated)...
$ firebase deploy

=== Deploying to '******'...

i  deploying functions
i  functions: ensuring necessary APIs are enabled...
i  runtimeconfig: ensuring necessary APIs are enabled...
✔  runtimeconfig: all necessary APIs are enabled
✔  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...
i  functions: packaged functions (34.95 KB) for uploading
✔  functions: functions folder uploaded successfully
i  starting release process (may take several minutes)...
i  functions: updating function ******...
✔  functions[******]: Successful update operation.
✔  functions: all functions deployed successfully!

✔  Deploy complete!

Project Console: https://console.firebase.google.com/project/******/overview
Function URL (******): https://us-*****1-******.cloudfunctions.net/******
✨  Done in 89.62s.
```

**Comment by laurenzlong** [comment]
@Swivelgames Can you try deploying with the new dependencies, it'll probably fail but print a more clear error message than what the local emulator will print.

**Comment by Swivelgames** [comment]
@laurenzlong Apologies, I wasn't specific. The deployment was successful with the latest versions. The local `firebase serve`, however, does not.

**Comment by laurenzlong** [comment]
No worries! Thanks for clarifying. I created a branch that has better error logging. Can you install it by running:

npm install -g https://github.com/firebase/firebase-tools.git#ll-printparsererr

Then run the local emulation again and let me know what the log looks like.

**Comment by Swivelgames** [comment]
w4t...

# Successful...?

```sh
$ yarn global remove firebase-tools
...(truncated)...
success Uninstalled packages.

$ yarn global add https://github.com/firebase/firebase-tools.git#ll-printparsererr
...(truncated)...
success Installed "firebase-tools@3.12.0" with binaries:
      - firebase

$ yarn start
...(truncated)...

=== Serving from '/******/Projects/node/******'...

i  functions: Preparing to emulate functions.
✔  functions: vuiagent: http://localhost:5000/*****/us-*****1/*****
```

# git diff v3.13.0 ll-printparsererr
w4t

```diff
diff --git a/lib/functionsEmulator.js b/lib/functionsEmulator.js
index 198dd7e..47bc596 100644
--- a/lib/functionsEmulator.js
+++ b/lib/functionsEmulator.js
@@ -187,7 +187,7 @@ FunctionsEmulator.prototype.start = function(shellMode) {
     }
   }).catch(function(e) {
     if (e) {
-      utils.logWarning(chalk.yellow('functions:') + ' Error from emulator. ' + e.stack);
+      utils.logWarning(chalk.yellow('functions:') + ' Error from emulator. ' + e);
     }
     return instance.stop();
   });
diff --git a/package.json b/package.json
index a5cfa2f..192425c 100644
--- a/package.json
+++ b/package.json
@@ -1,6 +1,6 @@
 {
   "name": "firebase-tools",
-  "version": "3.13.0",
+  "version": "3.12.0",
   "description": "Command-Line Interface for Firebase",
   "main": "index.js",
   "bin": {
```

# Caching Issue?

I guess I'll chalk this up to some sort of caching on some end. After attempting to install your `ll-printparsererr` branch, it "magically" started work. However, if you remember, [I posted about 45 minutes ago the same steps which still resulted in the errors](https://github.com/firebase/firebase-functions/issues/114#issuecomment-334245838).

# Going Back To `@latest`

```
$ yarn global remove firebase-tools
...(truncated)...
success Uninstalled packages.

$ yarn global add firebase-tools@latest
...(truncated)...
success Installed "firebase-tools@3.13.0" with binaries:
      - firebase

$ firebase --version
3.13.0

$ yarn start
...(truncated)...

=== Serving from '/******/Projects/node/******'...

i  functions: Preparing to emulate functions.
✔  functions: vuiagent: http://localhost:5000/*****/us-*****1/*****
```

And it's a success all of a sudden? w4t.

***Thanks for your magical touch, @laurenzlong !*** 🤣 

# Recommendation To Others

In the future, I'll probably run the following:
```
$ npm cache clean
$ yarn cache clean
```

I'm not sure *if* this was the real issue or *why*, but it all seems to be working now.

**Comment by laurenzlong** [comment]
Thanks for the update! Glad it works now :)
