### ISSUE TITLE
Having trouble after upgrade to 0.7.0

### ISSUE THREAD

**Issue by bagintz** [firebase/firebase-functions#117]
Converted my methods from database to firestore and updated admin to 5.4.1 and functions to 0.7.0
Getting:

```
Error: Error occurred while parsing your function triggers.

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/private/var/folders/cd/yldp31gs2997jqshrhy0_18c0000gn/T/fbfn_127862yZdNPUPHJDZ/node_modules/firebase-functions/lib/index.js:28:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

```

Where line 28 from that file is:
`const analytics = require("./providers/analytics");`

Any ideas?

**Comment by bagintz** [comment]
fwiw, I got this same thing on an empty "firebase init" project with just functions selected

**Comment by justinrosenthal** [comment]
What version of node do you have installed?

**Comment by bagintz** [comment]
@justinrosenthal I downgraded to 6+ based on what the firebase docs say 
`Cloud Functions runs Node v.6.11.1, so we recommend that you develop locally with this version.` 
(from https://firebase.google.com/docs/functions/get-started), but when I rebooted it seems that nvm reset it to 8.6.0 and now it works????
weird

**Comment by justinrosenthal** [comment]
Ok, since it's resolved I'm going to close this issue.  Please reopen if you feel there's a bug with `firebase-functions` that needs to be addressed.
