### ISSUE TITLE
[Beta] Cannot read properties of undefined (reading 'headers') (v2)

### ISSUE THREAD

**Issue by akauppi** [firebase/firebase-functions#1289]
### Related issues

May be related to #1282 - the error message is similar.

### [REQUIRED] Version info

**node:** n/a

**firebase-functions:** 4.0.1

**firebase-tools:** 11.15.0

**firebase-admin:** 11.2.0

### [REQUIRED] Test case

Sorry, no minimal test case. Follow the setup in #1288 (about 20 min).

### [REQUIRED] Steps to reproduce

```
$ git clone https://github.com/akauppi/GroundLevel-firebase-es.git
$ cd GroundLevel-firebase-es

$ git checkout next.sep22
$ make install

# Read README and `first/README.md`, at the least.
$ cd first
$ ./deploy.sh
```

### [REQUIRED] Expected behavior

Deployment would succeed, including the scheduled function `promBridge`.

If I'm doing something wrong, I expect to get an error message that describes the corrective action.

### [REQUIRED] Actual behavior

Deployment crashes, with:

```
i  functions: preparing codebase default for deployment

Error: Failed to load function definition from source: Failed to generate manifest from function source: TypeError: Cannot read properties of undefined (reading 'headers')
```

<details><summary>firebase-debug.log (tail is likely enough)</summary>

```
[debug] [2022-10-28T17:18:56.781Z] Building nodejs source
[debug] [2022-10-28T17:18:56.785Z] Could not find functions.yaml. Must use http discovery
[debug] [2022-10-28T17:18:57.418Z] Serving at port 9005

[debug] [2022-10-28T17:18:57.570Z] Initial load: {
  FIREBASE_CONFIG: '{"projectId":"groundlevel-sep22","databaseURL":"https://groundlevel-sep22-default-rtdb.europe-west1.firebasedatabase.app","storageBucket":"groundlevel-sep22.appspot.com","locationId":"europe-central2"}',
  GCLOUD_PROJECT: 'groundlevel-sep22',
  PORT: '9005',
  FUNCTIONS_CONTROL_API: 'true',
  HOME: '/root',
  PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
  CLOUD_RUNTIME_CONFIG: '{"firebase":{"projectId":"groundlevel-sep22","databaseURL":"https://groundlevel-sep22-default-rtdb.europe-west1.firebasedatabase.app","storageBucket":"groundlevel-sep22.appspot.com","locationId":"europe-central2"}}'
}

[debug] [2022-10-28T17:18:58.223Z] Got response from /__/functions.yaml Failed to generate manifest from function source: TypeError: Cannot read properties of undefined (reading 'headers')
[debug] [2022-10-28T17:18:58.234Z] Failed to parse functions.yaml incomplete explicit mapping pair; a key node is missed; or followed by a non-tabulated empty line at line 1, column 60:
     ...  from function source: TypeError: Cannot read properties of unde ... 
                                         ^ {"name":"YAMLException","reason":"incomplete explicit mapping pair; a key node is missed; or followed by a non-tabulated empty line","mark":{"name":null,"buffer":"Failed to generate manifest from function source: TypeError: Cannot read properties of undefined (reading 'headers')\n\u0000","position":59,"line":0,"column":59},"message":"incomplete explicit mapping pair; a key node is missed; or followed by a non-tabulated empty line at line 1, column 60:\n     ...  from function source: TypeError: Cannot read properties of unde ... \n                                         ^"}
[debug] [2022-10-28T17:18:58.237Z] shutdown requested via /__/quitquitquit

[error] 
[error] Error: Failed to load function definition from source: Failed to generate manifest from function source: TypeError: Cannot read properties of undefined (reading 'headers')
[debug] [2022-10-28T17:18:58.505Z] Error: EBUSY: resource busy or locked, unlink '/work/firebase-debug.log'
    at Object.unlinkSync (node:fs:1767:3)
    at process.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/firebase-tools/lib/bin/firebase.js:84:12)
    at process.emit (node:events:525:35)
    at process.exit (node:internal/process/per_thread:190:15)
    at Timeout._onTimeout (/usr/local/share/.config/yarn/global/node_modules/firebase-tools/lib/errorOut.js:20:17)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[error] 
[error] Error: An unexpected error has occurred.
```
</details>

### Were you able to successfully deploy your functions?

No.

**Comment by akauppi** [comment]
This turned out to be a mistake in my sources. Closing.

**Comment by milosmns** [comment]
@akauppi I'm the reporter of the other (seemingly) related issue; maybe you can post what you did to fix this? Maybe I have the same issue. 🙂 

But also... I think you should keep this issue open (or reopen it).
From what I read in your report - even if the issue was indeed in your own code and not in Firebase SDK, it looks like Firebase tooling failed to report the issue during the compile step. Ideally the whole pipeline should fail in the compile step, not during deployment, if you agree with me.

**Comment by milosmns** [comment]
Cool, thanks for expanding on that! Cheers 👋
