### ISSUE TITLE
functions.storage.object().onFinalize emulator error

### ISSUE THREAD

**Issue by RamsayGit** [firebase/firebase-functions#1299]
**node:** v16.15.0

**firebase-functions:** 11.16.0

**firebase-tools:** 11.16.0

**firebase-admin:** 11.2.0

I'm running the latest version of firebase emulators and everything launches fine with (**npm run build -- --watch | firebase emulators:start --inspect-functions**) functions trigger/execute normally until I upload a file to firebase storage which triggers the function 'processImages' and then nothing ever happens anymore, no other function ever triggers or runs again until i restart the whole emulator. A minute after uploading the file to storage I get the below exception. Any explanation of this and a way to fix it?

```
exports.processImages =
    functions.storage.object().onFinalize(async (object, context) => {
      return Promise.resolve<boolean>(true)
          .then((value) => console.log(">> hi")).catch(reason => {
            console.log(`>> error ${reason}`);
          });
    });
```

```
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: 5 NOT_FOUND: Topic not found
    at Object.callErrorFromStatus (C:\Users\ramsa\IdeaProjects\lets_hang\functions\node_modules\@grpc\grpc-js\build\src\call.js:31:19)
    at Object.onReceiveStatus (C:\Users\ramsa\IdeaProjects\lets_hang\functions\node_modules\@grpc\grpc-js\build\src\client.js:195:52)
    at Object.onReceiveStatus (C:\Users\ramsa\IdeaProjects\lets_hang\functions\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:365:141)
    at Object.onReceiveStatus (C:\Users\ramsa\IdeaProjects\lets_hang\functions\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:328:181)
    at C:\Users\ramsa\IdeaProjects\lets_hang\functions\node_modules\@grpc\grpc-js\build\src\call-stream.js:188:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (C:\Users\ramsa\IdeaProjects\lets_hang\functions\node_modules\@grpc\grpc-js\build\src\client.js:163:34)
    at ServiceClientImpl.<anonymous> (C:\Users\ramsa\IdeaProjects\lets_hang\functions\node_modules\@grpc\grpc-js\build\src\make-client.js:105:19)
    at C:\Users\ramsa\IdeaProjects\lets_hang\functions\node_modules\@google-cloud\pubsub\build\src\v1\publisher_client.js:214:29
    at C:\Users\ramsa\IdeaProjects\lets_hang\functions\node_modules\google-gax\build\src\normalCalls\timeout.js:44:16
    at repeat (C:\Users\ramsa\IdeaProjects\lets_hang\functions\node_modules\google-gax\build\src\normalCalls\retries.js:80:25)
    at C:\Users\ramsa\IdeaProjects\lets_hang\functions\node_modules\google-gax\build\src\normalCalls\retries.js:118:13
    at OngoingCall.call (C:\Users\ramsa\IdeaProjects\lets_hang\functions\node_modules\google-gax\build\src\call.js:67:27)
    at NormalApiCaller.call (C:\Users\ramsa\IdeaProjects\lets_hang\functions\node_modules\google-gax\build\src\normalCalls\normalApiCaller.js:34:19)
    at C:\Users\ramsa\IdeaProjects\lets_hang\functions\node_modules\google-gax\build\src\createApiCall.js:84:30 {
  code: 5,
  details: 'Topic not found',
  metadata: Metadata {
    internalRepr: Map(1) { 'content-type' => [ 'application/grpc' ] },
    options: {}
  },
  note: 'Exception occurred in retry method that was not classified as transient'
}
>  node:internal/process/promises:279
>              triggerUncaughtException(err, true /* fromPromise */);
>              ^
>
>  Error: 5 NOT_FOUND: Topic not found
>      at Object.callErrorFromStatus (C:\Users\ramsa\IdeaProjects\lets_hang\functions\node_modules\@grpc\grpc-js\build\src\call.js:31:19)
>      at Object.onReceiveStatus (C:\Users\ramsa\IdeaProjects\lets_hang\functions\node_modules\@grpc\grpc-js\build\src\client.js:195:52)
>      at Object.onReceiveStatus (C:\Users\ramsa\IdeaProjects\lets_hang\functions\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:365:141)
>      at Object.onReceiveStatus (C:\Users\ramsa\IdeaProjects\lets_hang\functions\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:328:181)
>      at C:\Users\ramsa\IdeaProjects\lets_hang\functions\node_modules\@grpc\grpc-js\build\src\call-stream.js:188:78
>      at processTicksAndRejections (node:internal/process/task_queues:78:11)
>  for call at
>      at ServiceClientImpl.makeUnaryRequest (C:\Users\ramsa\IdeaProjects\lets_hang\functions\node_modules\@grpc\grpc-js\build\src\client.js:163:34)
>      at ServiceClientImpl.<anonymous> (C:\Users\ramsa\IdeaProjects\lets_hang\functions\node_modules\@grpc\grpc-js\build\src\make-client.js:105:19)
>      at C:\Users\ramsa\IdeaProjects\lets_hang\functions\node_modules\@google-cloud\pubsub\build\src\v1\publisher_client.js:214:29
>      at C:\Users\ramsa\IdeaProjects\lets_hang\functions\node_modules\google-gax\build\src\normalCalls\timeout.js:44:16
>      at repeat (C:\Users\ramsa\IdeaProjects\lets_hang\functions\node_modules\google-gax\build\src\normalCalls\retries.js:80:25)
>      at C:\Users\ramsa\IdeaProjects\lets_hang\functions\node_modules\google-gax\build\src\normalCalls\retries.js:118:13
>      at OngoingCall.call (C:\Users\ramsa\IdeaProjects\lets_hang\functions\node_modules\google-gax\build\src\call.js:67:27)
>      at NormalApiCaller.call (C:\Users\ramsa\IdeaProjects\lets_hang\functions\node_modules\google-gax\build\src\normalCalls\normalApiCaller.js:34:19)
>      at C:\Users\ramsa\IdeaProjects\lets_hang\functions\node_modules\google-gax\build\src\createApiCall.js:84:30 {
>    code: 5,
>    details: 'Topic not found',
>    metadata: Metadata {
>      internalRepr: Map(1) { 'content-type' => [ 'application/grpc' ] },
>      options: {}
>    },
>    note: 'Exception occurred in retry method that was not classified as transient'
>  }
```

**Comment by RamsayGit** [comment]
In a process of trail and error to try pin the root of this problem I played around with the command **npm run build -- --watch | firebase emulators:start --inspect-functions** and I found that if I remove the **--inspect-functions** then the problem goes away, not sure why.. so this works fine **npm run build -- --watch | firebase emulators:start** but now I cannot debug my code.
