### ISSUE TITLE
Error on deploy: Failed to fetch Run service undefined

### ISSUE THREAD

**Issue by jerryMeng100** [firebase/firebase-functions#1326]
There seems to be an issue with Google-side Functions v1 to v2 upgrade. I don't think I tried to turn functions into v2 but some APIs called showed v2 things (or so I'm assuming) and it's throwing some weird errors. Can't deploy functions as of now. Logs below:

### [REQUIRED] Version info

**node: 16.18.1**

**firebase-functions:  4.0.0-rc.0**

**firebase-tools: 11.4.2**

**firebase-admin: 10.3.0**

### [REQUIRED] Test case

Nondeterministic, or at least unknown from my side. I have 2 Firebase projects for different envs, and production environment was blocked due to this error, but staging was able to deploy fine.

### [REQUIRED] Steps to reproduce

Deploy functions

### [REQUIRED] Expected behavior

Run smoothly

### [REQUIRED] Actual behavior

Logs:

Only included the final few lines that seemed to error out as other API calls seemed fine:

```
[2022-12-11T03:20:17.338Z] >>> [apiv2][query] GET https://cloudfunctions.googleapis.com/v2alpha/projects/redacted-app/locations/-/functions [none]
[2022-12-11T03:20:17.959Z] <<< [apiv2][status] GET https://cloudfunctions.googleapis.com/v2alpha/projects/redacted-app/locations/-/functions 200
[2022-12-11T03:20:17.959Z] <<< [apiv2][body] GET https://cloudfunctions.googleapis.com/v2alpha/projects/redacted-app/locations/-/functions {"functions":[{"name":"projects/redacted-app/locations/us-central1/functions/getVideoProcessingStatus","buildConfig":{"build":"projects/167815696119/locations/us-central1/builds/7612d615-1bc3-40a2-a1d0-d34ab0028b8d","runtime":"nodejs16","entryPoint":"getVideoProcessingStatus","source":{"storageSource":{"bucket":"uploads-170828651943.us-central1.cloudfunctions.appspot.com","object":"4ca83c2a-1dde-4d13-a686-c34368264b62.zip"}},"sourceProvenance":{},"dockerRegistry":"ARTIFACT_REGISTRY"},"serviceConfig":{"timeoutSeconds":60,"environmentVariables":{"ENV":"production","FIREBASE_CONFIG":"{\"projectId\":\"redacted-app\",\"storageBucket\":\"redacted-app.appspot.com\",\"locationId\":\"us-central\"}","GCLOUD_PROJECT":"redacted-app"},"ingressSettings":"ALLOW_ALL","uri":"https://us-central1-redacted-app.cloudfunctions.net/getVideoProcessingStatus","availableMemory":"256M","revision":"21","maxInstanceRequestConcurrency":1,"securityLevel":"SECURE_ALWAYS"},"state":"ACTIVE","updateTime":"2022-12-05T22:06:47.862610Z","labels":{"deployment-tool":"cli-firebase","deployment-callable":"true"},"environment":"GEN_1"},{"name":"projects/redacted-app/locations/us-central1/functions/setUsername","buildConfig":{"build":"projects/167815696119/locations/us-central1/builds/7612d615-1bc3-40a2-a1d0-d34ab0028b8d","runtime":"nodejs16","entryPoint":"setUsername","source":{"storageSource":{"bucket":"uploads-170828651943.us-central1.cloudfunctions.appspot.com","object":"4ca83c2a-1dde-4d13-a686-c34368264b62.zip"}},"sourceProvenance":{},"dockerRegistry":"ARTIFACT_REGISTRY"},"serviceConfig":{"timeoutSeconds":60,"environmentVariables":{"ENV":"production","FIREBASE_CONFIG":"{\"projectId\":\"redacted-app\",\"storageBucket\":\"redacted-app.appspot.com\",\"locationId\":\"us-central\"}","GCLOUD_PROJECT":"redacted-app"},"ingressSettings":"ALLOW_ALL","uri":"https://us-central1-redacted-app.cloudfunctions.net/setUsername","availableMemory":"256M","revision":"23","maxInstanceRequestConcurrency":1,"securityLevel":"SECURE_ALWAYS"},"state":"ACTIVE","updateTime":"2022-12-05T22:06:47.904691Z","labels":{"deployment-callable":"true","deployment-tool":"cli-firebase"},"environment":"GEN_1"},{"name":"projects/redacted-app/locations/us-central1/functions/onCreateReview","buildConfig":{"build":"projects/167815696119/locations/us-central1/builds/7612d615-1bc3-40a2-a1d0-d34ab0028b8d","runtime":"nodejs16","entryPoint":"onCreateReview","source":{"storageSource":{"bucket":"uploads-170828651943.us-central1.cloudfunctions.appspot.com","object":"4ca83c2a-1dde-4d13-a686-c34368264b62.zip"}},"sourceProvenance":{},"dockerRegistry":"ARTIFACT_REGISTRY"},"serviceConfig":{"timeoutSeconds":60,"environmentVariables":{"ENV":"production","FIREBASE_CONFIG":"{\"projectId\":\"redacted-app\",\"storageBucket\":\"redacted-app.appspot.com\",\"locationId\":\"us-central\"}","GCLOUD_PROJECT":"redacted-app"},"ingressSettings":"ALLOW_ALL","availableMemory":"256M","revision":"22","maxInstanceRequestConcurrency":1},"eventTrigger":{"eventType":"providers/cloud.firestore/eventTypes/document.create","eventFilters":[{"attribute":"resource","value":"projects/redacted-app/databases/(default)/documents/Reviews/{id}"}]},"state":"ACTIVE","updateTime":"2022-12-05T22:06:47.874931Z","labels":{"deployment-tool":"cli-firebase"},"environment":"GEN_1"},{"name":"projects/redacted-app/locations/us-central1/functions/likeContent","buildConfig":{"build":"projects/167815696119/locations/us-central1/builds/7612d615-1bc3-40a2-a1d0-d34ab0028b8d","runtime":"nodejs16","entryPoint":"likeContent","source":{"storageSource":{"bucket":"uploads-170828651943.us-central1.cloudfunctions.appspot.com","object":"4ca83c2a-1dde-4d13-a686-c34368264b62.zip"}},"sourceProvenance":{},"dockerRegistry":"ARTIFACT_REGISTRY"},"serviceConfig":{"timeoutSeconds":60,"environmentVariables":{"ENV":"production","FIREBASE_CONFIG":"{\"projectId\":\"redacted-app\",\"storageBucket\":\"redacted-app.appspot.com\",\"locationId\":\"us-central\"}","GCLOUD_PROJECT":"redacted-app"},"ingressSettings":"ALLOW_ALL","uri":"https://us-central1-redacted-app.cloudfunctions.net/likeContent","availableMemory":"256M","revision":"23","maxInstanceRequestConcurrency":1,"securityLevel":"SECURE_ALWAYS"},"state":"ACTIVE","updateTime":"2022-12-05T22:06:47.862797Z","labels":{"deployment-tool":"cli-firebase","deployment-callable":"true"},"environment":"GEN_1"},{"name":"projects/redacted-app/locations/us-central1/functions/follow","buildConfig":{"build":"projects/167815696119/locations/us-central1/builds/7612d615-1bc3-40a2-a1d0-d34ab0028b8d","runtime":"nodejs16","entryPoint":"follow","source":{"storageSource":{"bucket":"uploads-170828651943.us-central1.cloudfunctions.appspot.com","object":"4ca83c2a-1dde-4d13-a686-c34368264b62.zip"}},"sourceProvenance":{},"dockerRegistry":"ARTIFACT_REGISTRY"},"serviceConfig":{"timeoutSeconds":60,"environmentVariables":{"ENV":"production","FIREBASE_CONFIG":"{\"projectId\":\"redacted-app\",\"storageBucket\":\"redacted-app.appspot.com\",\"locationId\":\"us-central\"}","GCLOUD_PROJECT":"redacted-app"},"ingressSettings":"ALLOW_ALL","uri":"https://us-central1-redacted-app.cloudfunctions.net/follow","availableMemory":"256M","revision":"23","maxInstanceRequestConcurrency":1,"securityLevel":"SECURE_ALWAYS"},"state":"ACTIVE","updateTime":"2022-12-05T22:06:47.863384Z","labels":{"deployment-tool":"cli-firebase","deployment-callable":"true"},"environment":"GEN_1"},{"name":"projects/redacted-app/locations/us-central1/functions/blockUser","buildConfig":{"build":"projects/167815696119/locations/us-central1/builds/7612d615-1bc3-40a2-a1d0-d34ab0028b8d","runtime":"nodejs16","entryPoint":"blockUser","source":{"storageSource":{"bucket":"uploads-170828651943.us-central1.cloudfunctions.appspot.com","object":"4ca83c2a-1dde-4d13-a686-c34368264b62.zip"}},"sourceProvenance":{},"dockerRegistry":"ARTIFACT_REGISTRY"},"serviceConfig":{"timeoutSeconds":60,"environmentVariables":{"ENV":"production","FIREBASE_CONFIG":"{\"projectId\":\"redacted-app\",\"storageBucket\":\"redacted-app.appspot.com\",\"locationId\":\"us-central\"}","GCLOUD_PROJECT":"redacted-app"},"ingressSettings":"ALLOW_ALL","uri":"https://us-central1-redacted-app.cloudfunctions.net/blockUser","serviceAccountEmail":"redacted-app@appspot.gserviceaccount.com","availableMemory":"256M","revision":"9","maxInstanceRequestConcurrency":1,"securityLevel":"SECURE_ALWAYS"},"state":"ACTIVE","updateTime":"2022-12-05T22:06:47.808786Z","labels":{"deployment-tool":"cli-firebase","deployment-callable":"true"},"environment":"GEN_1"},{"name":"projects/redacted-app/locations/us-central1/functions/saveReview","buildConfig":{"build":"projects/167815696119/locations/us-central1/builds/7612d615-1bc3-40a2-a1d0-d34ab0028b8d","runtime":"nodejs16","entryPoint":"saveReview","source":{"storageSource":{"bucket":"uploads-170828651943.us-central1.cloudfunctions.appspot.com","object":"4ca83c2a-1dde-4d13-a686-c34368264b62.zip"}},"sourceProvenance":{},"dockerRegistry":"ARTIFACT_REGISTRY"},"serviceConfig":{"timeoutSeconds":60,"environmentVariables":{"ENV":"production","FIREBASE_CONFIG":"{\"projectId\":\"redacted-app\",\"storageBucket\":\"redacted-app.appspot.com\",\"locationId\":\"us-central\"}","GCLOUD_PROJECT":"redacted-app"},"ingressSettings":"ALLOW_ALL","uri":"https://us-central1-redacted-app.cloudfunctions.net/saveReview","availableMemory":"256M","revision":"23","maxInstanceRequestConcurrency":1,"securityLevel":"SECURE_ALWAYS"},"state":"ACTIVE","updateTime":"2022-12-05T22:06:47.894865Z","labels":{"deployment-tool":"cli-firebase","deployment-callable":"true"},"environment":"GEN_1"},{"name":"projects/redacted-app/locations/us-central1/functions/uploadVideoRequest","buildConfig":{"build":"projects/167815696119/locations/us-central1/builds/7612d615-1bc3-40a2-a1d0-d34ab0028b8d","runtime":"nodejs16","entryPoint":"uploadVideoRequest","source":{"storageSource":{"bucket":"uploads-170828651943.us-central1.cloudfunctions.appspot.com","object":"4ca83c2a-1dde-4d13-a686-c34368264b62.zip"}},"sourceProvenance":{},"dockerRegistry":"ARTIFACT_REGISTRY"},"serviceConfig":{"timeoutSeconds":60,"environmentVariables":{"ENV":"production","FIREBASE_CONFIG":"{\"projectId\":\"redacted-app\",\"storageBucket\":\"redacted-app.appspot.com\",\"locationId\":\"us-central\"}","GCLOUD_PROJECT":"redacted-app"},"ingressSettings":"ALLOW_ALL","uri":"https://us-central1-redacted-app.cloudfunctions.net/uploadVideoRequest","availableMemory":"256M","revision":"23","maxInstanceRequestConcurrency":1,"securityLevel":"SECURE_ALWAYS"},"state":"ACTIVE","updateTime":"2022-12-05T22:06:47.908375Z","labels":{"deployment-tool":"cli-firebase","deployment-callable":"true"},"environment":"GEN_1"},{"name":"projects/redacted-app/locations/us-central1/functions/deleteContent","buildConfig":{"build":"projects/167815696119/locations/us-central1/builds/7612d615-1bc3-40a2-a1d0-d34ab0028b8d","runtime":"nodejs16","entryPoint":"deleteContent","source":{"storageSource":{"bucket":"uploads-170828651943.us-central1.cloudfunctions.appspot.com","object":"4ca83c2a-1dde-4d13-a686-c34368264b62.zip"}},"sourceProvenance":{},"dockerRegistry":"ARTIFACT_REGISTRY"},"serviceConfig":{"timeoutSeconds":60,"environmentVariables":{"ENV":"production","FIREBASE_CONFIG":"{\"projectId\":\"redacted-app\",\"storageBucket\":\"redacted-app.appspot.com\",\"locationId\":\"us-central\"}","GCLOUD_PROJECT":"redacted-app"},"ingressSettings":"ALLOW_ALL","uri":"https://us-central1-redacted-app.cloudfunctions.net/deleteContent","availableMemory":"256M","revision":"23","maxInstanceRequestConcurrency":1,"securityLevel":"SECURE_ALWAYS"},"state":"ACTIVE","updateTime":"2022-12-05T22:06:47.862851Z","labels":{"deployment-tool":"cli-firebase","deployment-callable":"true"},"environment":"GEN_1"},{"name":"projects/redacted-app/locations/us-central1/functions/commentReview","buildConfig":{"build":"projects/167815696119/locations/us-central1/builds/7612d615-1bc3-40a2-a1d0-d34ab0028b8d","runtime":"nodejs16","entryPoint":"commentReview","source":{"storageSource":{"bucket":"uploads-170828651943.us-central1.cloudfunctions.appspot.com","object":"4ca83c2a-1dde-4d13-a686-c34368264b62.zip"}},"sourceProvenance":{},"dockerRegistry":"ARTIFACT_REGISTRY"},"serviceConfig":{"timeoutSeconds":60,"environmentVariables":{"ENV":"production","FIREBASE_CONFIG":"{\"projectId\":\"redacted-app\",\"storageBucket\":\"redacted-app.appspot.com\",\"locationId\":\"us-central\"}","GCLOUD_PROJECT":"redacted-app"},"ingressSettings":"ALLOW_ALL","uri":"https://us-central1-redacted-app.cloudfunctions.net/commentReview","availableMemory":"256M","revision":"23","maxInstanceRequestConcurrency":1,"securityLevel":"SECURE_ALWAYS"},"state":"ACTIVE","updateTime":"2022-12-05T22:06:47.860768Z","labels":{"deployment-tool":"cli-firebase","deployment-callable":"true"},"environment":"GEN_1"},{"name":"projects/redacted-app/locations/us-central1/functions/shareReview","buildConfig":{"build":"projects/167815696119/locations/us-central1/builds/7612d615-1bc3-40a2-a1d0-d34ab0028b8d","runtime":"nodejs16","entryPoint":"shareReview","source":{"storageSource":{"bucket":"uploads-170828651943.us-central1.cloudfunctions.appspot.com","object":"4ca83c2a-1dde-4d13-a686-c34368264b62.zip"}},"sourceProvenance":{},"dockerRegistry":"ARTIFACT_REGISTRY"},"serviceConfig":{"timeoutSeconds":60,"environmentVariables":{"ENV":"production","FIREBASE_CONFIG":"{\"projectId\":\"redacted-app\",\"storageBucket\":\"redacted-app.appspot.com\",\"locationId\":\"us-central\"}","GCLOUD_PROJECT":"redacted-app"},"ingressSettings":"ALLOW_ALL","uri":"https://us-central1-redacted-app.cloudfunctions.net/shareReview","availableMemory":"256M","revision":"23","maxInstanceRequestConcurrency":1,"securityLevel":"SECURE_ALWAYS"},"state":"ACTIVE","updateTime":"2022-12-05T22:06:47.904690Z","labels":{"deployment-tool":"cli-firebase","deployment-callable":"true"},"environment":"GEN_1"},{"name":"projects/redacted-app/locations/us-central1/functions/videoEngageAnalytics","buildConfig":{"build":"projects/167815696119/locations/us-central1/builds/7612d615-1bc3-40a2-a1d0-d34ab0028b8d","runtime":"nodejs16","entryPoint":"videoEngageAnalytics","source":{"storageSource":{"bucket":"uploads-170828651943.us-central1.cloudfunctions.appspot.com","object":"4ca83c2a-1dde-4d13-a686-c34368264b62.zip"}},"sourceProvenance":{},"dockerRegistry":"ARTIFACT_REGISTRY"},"serviceConfig":{"timeoutSeconds":60,"environmentVariables":{"ENV":"production","FIREBASE_CONFIG":"{\"projectId\":\"redacted-app\",\"storageBucket\":\"redacted-app.appspot.com\",\"locationId\":\"us-central\"}","GCLOUD_PROJECT":"redacted-app"},"ingressSettings":"ALLOW_ALL","uri":"https://us-central1-redacted-app.cloudfunctions.net/videoEngageAnalytics","availableMemory":"256M","revision":"13","maxInstanceRequestConcurrency":1,"securityLevel":"SECURE_ALWAYS"},"state":"ACTIVE","updateTime":"2022-12-05T22:06:47.913058Z","labels":{"deployment-tool":"cli-firebase","deployment-callable":"true"},"environment":"GEN_1"},{"name":"projects/redacted-app/locations/us-central1/functions/onCreateUser","buildConfig":{"build":"projects/167815696119/locations/us-central1/builds/7612d615-1bc3-40a2-a1d0-d34ab0028b8d","runtime":"nodejs16","entryPoint":"onCreateUser","source":{"storageSource":{"bucket":"uploads-170828651943.us-central1.cloudfunctions.appspot.com","object":"4ca83c2a-1dde-4d13-a686-c34368264b62.zip"}},"sourceProvenance":{},"dockerRegistry":"ARTIFACT_REGISTRY"},"serviceConfig":{"timeoutSeconds":60,"environmentVariables":{"ENV":"production","FIREBASE_CONFIG":"{\"projectId\":\"redacted-app\",\"storageBucket\":\"redacted-app.appspot.com\",\"locationId\":\"us-central\"}","GCLOUD_PROJECT":"redacted-app"},"ingressSettings":"ALLOW_ALL","availableMemory":"256M","revision":"21","maxInstanceRequestConcurrency":1},"eventTrigger":{"eventType":"providers/cloud.firestore/eventTypes/document.create","eventFilters":[{"attribute":"resource","value":"projects/redacted-app/databases/(default)/documents/UserPublic/{uid}"}]},"state":"ACTIVE","updateTime":"2022-12-05T22:06:47.885536Z","labels":{"deployment-tool":"cli-firebase"},"environment":"GEN_1"},{"name":"projects/redacted-app/locations/us-central1/functions/httpFunctions","buildConfig":{"build":"projects/167815696119/locations/us-central1/builds/7612d615-1bc3-40a2-a1d0-d34ab0028b8d","runtime":"nodejs16","entryPoint":"httpFunctions","source":{"storageSource":{"bucket":"uploads-170828651943.us-central1.cloudfunctions.appspot.com","object":"4ca83c2a-1dde-4d13-a686-c34368264b62.zip"}},"sourceProvenance":{},"dockerRegistry":"ARTIFACT_REGISTRY"},"serviceConfig":{"timeoutSeconds":60,"environmentVariables":{"ENV":"production","FIREBASE_CONFIG":"{\"projectId\":\"redacted-app\",\"storageBucket\":\"redacted-app.appspot.com\",\"locationId\":\"us-central\"}","GCLOUD_PROJECT":"redacted-app"},"ingressSettings":"ALLOW_ALL","uri":"https://us-central1-redacted-app.cloudfunctions.net/httpFunctions","availableMemory":"256M","revision":"17","maxInstanceRequestConcurrency":1,"securityLevel":"SECURE_ALWAYS"},"state":"ACTIVE","updateTime":"2022-12-05T22:06:47.863800Z","labels":{"deployment-tool":"cli-firebase"},"environment":"GEN_1"},{"name":"projects/redacted-app/locations/us-central1/functions/createReview","buildConfig":{"build":"projects/167815696119/locations/us-central1/builds/7612d615-1bc3-40a2-a1d0-d34ab0028b8d","runtime":"nodejs16","entryPoint":"createReview","source":{"storageSource":{"bucket":"uploads-170828651943.us-central1.cloudfunctions.appspot.com","object":"4ca83c2a-1dde-4d13-a686-c34368264b62.zip"}},"sourceProvenance":{},"dockerRegistry":"ARTIFACT_REGISTRY"},"serviceConfig":{"timeoutSeconds":60,"environmentVariables":{"ENV":"production","FIREBASE_CONFIG":"{\"projectId\":\"redacted-app\",\"storageBucket\":\"redacted-app.appspot.com\",\"locationId\":\"us-central\"}","GCLOUD_PROJECT":"redacted-app"},"ingressSettings":"ALLOW_ALL","uri":"https://us-central1-redacted-app.cloudfunctions.net/createReview","availableMemory":"256M","revision":"23","maxInstanceRequestConcurrency":1,"securityLevel":"SECURE_ALWAYS"},"state":"ACTIVE","updateTime":"2022-12-05T22:06:47.861360Z","labels":{"deployment-tool":"cli-firebase","deployment-callable":"true"},"environment":"GEN_1"},{"name":"projects/redacted-app/locations/us-central1/functions/ext-firestore-reviews-search-executeIndexOperation","description":"Firestore document-triggered function that creates, updates, or deletes data in Algolia.","buildConfig":{"build":"projects/167815696119/locations/us-central1/builds/f7720dc2-3284-40b6-a06f-5fa147f1a77c","runtime":"nodejs10","entryPoint":"executeIndexOperation","source":{"storageSource":{"bucket":"firebase-mod-sources-prod","object":"0a50813c979c2b95076a5358d1e216bd475cd167fb22a693271cbba4282b66bc"}},"sourceProvenance":{},"dockerRegistry":"ARTIFACT_REGISTRY"},"serviceConfig":{"timeoutSeconds":60,"environmentVariables":{"ALGOLIA_APP_ID":"HSY5VOGL3G","ALGOLIA_INDEX_NAME":"Reviews","COLLECTION_PATH":"Reviews","DATABASE_INSTANCE":"","DATABASE_URL":"","EXT_INSTANCE_ID":"firestore-reviews-search","FIREBASE_CONFIG":"{\"projectId\":\"redacted-app\",\"databaseURL\":\"\",\"storageBucket\":\"redacted-app.appspot.com\"}","FORCE_DATA_SYNC":"no","LOCATION":"us-central1","PROJECT_ID":"redacted-app","STORAGE_BUCKET":"redacted-app.appspot.com"},"ingressSettings":"ALLOW_INTERNAL_ONLY","serviceAccountEmail":"ext-firestore-reviews-search@redacted-app.iam.gserviceaccount.com","availableMemory":"256M","secretEnvironmentVariables":[{"key":"ALGOLIA_API_KEY","projectId":"167815696119","secret":"firestore-reviews-search-ALGOLIA_API_KEY","version":"1"}],"revision":"2","maxInstanceRequestConcurrency":1},"eventTrigger":{"eventType":"providers/cloud.firestore/eventTypes/document.write","eventFilters":[{"attribute":"resource","value":"projects/redacted-app/databases/(default)/documents/Reviews/{documentID}"}]},"state":"ACTIVE","updateTime":"2022-12-05T22:06:47.862386Z","labels":{"goog-firebase-ext":"firestore-algolia-search","deployment-tool":"firebase-extensions","goog-firebase-ext-iid":"firestore-reviews-search","firebase-extensions-ar":"enabled","goog-dm":"firebase-ext-firestore-reviews-search"},"environment":"GEN_1"},{"name":"projects/redacted-app/locations/us-central1/functions/deleteAccount","buildConfig":{"build":"projects/167815696119/locations/us-central1/builds/7612d615-1bc3-40a2-a1d0-d34ab0028b8d","runtime":"nodejs16","entryPoint":"deleteAccount","source":{"storageSource":{"bucket":"uploads-170828651943.us-central1.cloudfunctions.appspot.com","object":"4ca83c2a-1dde-4d13-a686-c34368264b62.zip"}},"sourceProvenance":{},"dockerRegistry":"ARTIFACT_REGISTRY"},"serviceConfig":{"timeoutSeconds":60,"environmentVariables":{"ENV":"production","FIREBASE_CONFIG":"{\"projectId\":\"redacted-app\",\"storageBucket\":\"redacted-app.appspot.com\",\"locationId\":\"us-central\"}","GCLOUD_PROJECT":"redacted-app"},"ingressSettings":"ALLOW_ALL","uri":"https://us-central1-redacted-app.cloudfunctions.net/deleteAccount","availableMemory":"256M","revision":"23","maxInstanceRequestConcurrency":1,"securityLevel":"SECURE_ALWAYS"},"state":"ACTIVE","updateTime":"2022-12-05T22:06:47.862361Z","labels":{"deployment-tool":"cli-firebase","deployment-callable":"true"},"environment":"GEN_1"},{"name":"projects/redacted-app/locations/us-central1/functions/flagContent","buildConfig":{"build":"projects/167815696119/locations/us-central1/builds/7612d615-1bc3-40a2-a1d0-d34ab0028b8d","runtime":"nodejs16","entryPoint":"flagContent","source":{"storageSource":{"bucket":"uploads-170828651943.us-central1.cloudfunctions.appspot.com","object":"4ca83c2a-1dde-4d13-a686-c34368264b62.zip"}},"sourceProvenance":{},"dockerRegistry":"ARTIFACT_REGISTRY"},"serviceConfig":{"timeoutSeconds":60,"environmentVariables":{"ENV":"production","FIREBASE_CONFIG":"{\"projectId\":\"redacted-app\",\"storageBucket\":\"redacted-app.appspot.com\",\"locationId\":\"us-central\"}","GCLOUD_PROJECT":"redacted-app"},"ingressSettings":"ALLOW_ALL","uri":"https://us-central1-redacted-app.cloudfunctions.net/flagContent","availableMemory":"256M","revision":"22","maxInstanceRequestConcurrency":1,"securityLevel":"SECURE_ALWAYS"},"state":"ACTIVE","updateTime":"2022-12-05T22:06:47.863314Z","labels":{"deployment-tool":"cli-firebase","deployment-callable":"true"},"environment":"GEN_1"},{"name":"projects/redacted-app/locations/us-central1/functions/sendUserFeedback","buildConfig":{"build":"projects/167815696119/locations/us-central1/builds/7612d615-1bc3-40a2-a1d0-d34ab0028b8d","runtime":"nodejs16","entryPoint":"sendUserFeedback","source":{"storageSource":{"bucket":"uploads-170828651943.us-central1.cloudfunctions.appspot.com","object":"4ca83c2a-1dde-4d13-a686-c34368264b62.zip"}},"sourceProvenance":{},"dockerRegistry":"ARTIFACT_REGISTRY"},"serviceConfig":{"timeoutSeconds":60,"environmentVariables":{"ENV":"production","FIREBASE_CONFIG":"{\"projectId\":\"redacted-app\",\"storageBucket\":\"redacted-app.appspot.com\",\"locationId\":\"us-central\"}","GCLOUD_PROJECT":"redacted-app"},"ingressSettings":"ALLOW_ALL","uri":"https://us-central1-redacted-app.cloudfunctions.net/sendUserFeedback","availableMemory":"256M","revision":"15","maxInstanceRequestConcurrency":1,"securityLevel":"SECURE_ALWAYS"},"state":"ACTIVE","updateTime":"2022-12-05T22:06:47.900433Z","labels":{"deployment-tool":"cli-firebase","deployment-callable":"true"},"environment":"GEN_1"},{"name":"projects/redacted-app/locations/us-central1/functions/viewReview","buildConfig":{"build":"projects/167815696119/locations/us-central1/builds/7612d615-1bc3-40a2-a1d0-d34ab0028b8d","runtime":"nodejs16","entryPoint":"viewReview","source":{"storageSource":{"bucket":"uploads-170828651943.us-central1.cloudfunctions.appspot.com","object":"4ca83c2a-1dde-4d13-a686-c34368264b62.zip"}},"sourceProvenance":{},"dockerRegistry":"ARTIFACT_REGISTRY"},"serviceConfig":{"timeoutSeconds":60,"environmentVariables":{"ENV":"production","FIREBASE_CONFIG":"{\"projectId\":\"redacted-app\",\"storageBucket\":\"redacted-app.appspot.com\",\"locationId\":\"us-central\"}","GCLOUD_PROJECT":"redacted-app"},"ingressSettings":"ALLOW_ALL","uri":"https://us-central1-redacted-app.cloudfunctions.net/viewReview","availableMemory":"256M","revision":"23","maxInstanceRequestConcurrency":1,"securityLevel":"SECURE_ALWAYS"},"state":"ACTIVE","updateTime":"2022-12-05T22:06:47.920181Z","labels":{"deployment-tool":"cli-firebase","deployment-callable":"true"},"environment":"GEN_1"},{"name":"projects/redacted-app/locations/us-central1/functions/ext-firestore-algolia-search-executeIndexOperation","description":"Firestore document-triggered function that creates, updates, or deletes data in Algolia.","buildConfig":{"build":"projects/167815696119/locations/us-central1/builds/6ad0d858-cf5d-4d14-afd4-9dff9647f6f7","runtime":"nodejs10","entryPoint":"executeIndexOperation","source":{"storageSource":{"bucket":"firebase-mod-sources-prod","object":"0a50813c979c2b95076a5358d1e216bd475cd167fb22a693271cbba4282b66bc"}},"sourceProvenance":{},"dockerRegistry":"ARTIFACT_REGISTRY"},"serviceConfig":{"timeoutSeconds":60,"environmentVariables":{"ALGOLIA_APP_ID":"HSY5VOGL3G","ALGOLIA_INDEX_NAME":"UserPublic","COLLECTION_PATH":"UserPublic","DATABASE_INSTANCE":"","DATABASE_URL":"","EXT_INSTANCE_ID":"firestore-algolia-search","FIREBASE_CONFIG":"{\"projectId\":\"redacted-app\",\"databaseURL\":\"\",\"storageBucket\":\"redacted-app.appspot.com\"}","FORCE_DATA_SYNC":"no","LOCATION":"us-central1","PROJECT_ID":"redacted-app","STORAGE_BUCKET":"redacted-app.appspot.com"},"ingressSettings":"ALLOW_INTERNAL_ONLY","serviceAccountEmail":"ext-firestore-algolia-search@redacted-app.iam.gserviceaccount.com","availableMemory":"256M","secretEnvironmentVariables":[{"key":"ALGOLIA_API_KEY","projectId":"167815696119","secret":"firestore-algolia-search-ALGOLIA_API_KEY","version":"1"}],"revision":"2","maxInstanceRequestConcurrency":1},"eventTrigger":{"eventType":"providers/cloud.firestore/eventTypes/document.write","eventFilters":[{"attribute":"resource","value":"projects/redacted-app/databases/(default)/documents/UserPublic/{documentID}"}]},"state":"ACTIVE","updateTime":"2022-12-05T22:06:47.862923Z","labels":{"deployment-tool":"firebase-extensions","goog-firebase-ext-iid":"firestore-algolia-search","firebase-extensions-ar":"enabled","goog-dm":"firebase-ext-firestore-algolia-search","goog-firebase-ext":"firestore-algolia-search"},"environment":"GEN_1"},{"name":"projects/redacted-app/locations/us-central1/functions/getVideoAsset","buildConfig":{"build":"projects/167815696119/locations/us-central1/builds/7612d615-1bc3-40a2-a1d0-d34ab0028b8d","runtime":"nodejs16","entryPoint":"getVideoAsset","source":{"storageSource":{"bucket":"uploads-170828651943.us-central1.cloudfunctions.appspot.com","object":"4ca83c2a-1dde-4d13-a686-c34368264b62.zip"}},"sourceProvenance":{},"dockerRegistry":"ARTIFACT_REGISTRY"},"serviceConfig":{"timeoutSeconds":60,"environmentVariables":{"ENV":"production","FIREBASE_CONFIG":"{\"projectId\":\"redacted-app\",\"storageBucket\":\"redacted-app.appspot.com\",\"locationId\":\"us-central\"}","GCLOUD_PROJECT":"redacted-app"},"ingressSettings":"ALLOW_ALL","uri":"https://us-central1-redacted-app.cloudfunctions.net/getVideoAsset","availableMemory":"256M","revision":"22","maxInstanceRequestConcurrency":1,"securityLevel":"SECURE_ALWAYS"},"state":"ACTIVE","updateTime":"2022-12-05T22:06:47.863641Z","labels":{"deployment-tool":"cli-firebase","deployment-callable":"true"},"environment":"GEN_1"}]}
[2022-12-11T03:20:18.026Z] FirebaseError: Failed to make request: Cannot read properties of undefined (reading 'startsWith')
    at Client.request (/usr/local/lib/node_modules/firebase-tools/lib/apiv2.js:112:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.getService (/usr/local/lib/node_modules/firebase-tools/lib/gcp/run.js:17:26)
    at async Promise.all (index 0)
    at async loadExistingBackend (/usr/local/lib/node_modules/firebase-tools/lib/deploy/functions/backend.js:199:28)
    at async Object.existingBackend (/usr/local/lib/node_modules/firebase-tools/lib/deploy/functions/backend.js:175:9)
    at async prepare (/usr/local/lib/node_modules/firebase-tools/lib/deploy/functions/prepare.js:110:115)
    at async chain (/usr/local/lib/node_modules/firebase-tools/lib/deploy/index.js:33:9)
    at async deploy (/usr/local/lib/node_modules/firebase-tools/lib/deploy/index.js:68:5)

Error: Failed to fetch Run service undefined

```

### Were you able to successfully deploy your functions?

No

**Comment by jerryMeng100** [comment]
Oops seems like my global firebase-tools was out of date - updated to @latest and worked.
