### ISSUE TITLE
Functions initialisation with const gives error

### ISSUE THREAD

**Issue by abhinavlal** [firebase/firebase-functions#14]
```js
const functions = require('firebase-functions');

const admin = require('firebase-admin');
admin.initializeApp(functions.config().firebase);

exports.CreateUser = functions.auth.user().onCreate(event => {
  console.log('User Created');
});
```

When deploying this function i  get error 
```

Error: Error occurred while parsing your function triggers.

SyntaxError: missing ) after argument list
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/firebase-tools/lib/triggerParser.js:16:9)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
```

changing `const functions` to `var functions` make this works.

firebase cli - 3.5.0
node - 3.3.1

**Comment by mbleigh** [comment]
You need to upgrade to node 6 to use es6 features like const
