### ISSUE TITLE
Unable to send response from cloud function called via http request

### ISSUE THREAD

**Issue by MattOutdore** [firebase/firebase-functions#1403]
### [REQUIRED] Version info

node: 18

firebase-functions: 4.4.0
firebase-admin: 11.8.0

### [REQUIRED] Test case

```
export const exportedFunction = functions
  .region("europe-west2")
  .https
  .onRequest(async (request, reponse) => {
    response.status(200)
      .header({
        "Accept": "*/*",
        "Content-Type": "text/plain",
      }).send("hello!");
  });
```

### [REQUIRED] Steps to reproduce

Send a GET request to the function endpoint

### [REQUIRED] Expected behavior

Should return "hello!"

### [REQUIRED] Actual behavior

I'm receiving this error consistently in the cloud functions log

```
"TypeError: Cannot set properties of undefined (setting 'accept')
    at ServerResponse.setHeader (node:_http_outgoing:654:45)
    at ServerResponse.header (/workspace/node_modules/express/lib/response.js:794:10)
    at ServerResponse.header (/workspace/node_modules/express/lib/response.js:797:12)"
```

### Were you able to successfully deploy your functions?

No issues with deploying the function

**Comment by MattOutdore** [comment]
Figured it out, vs code ended up importing response from the express package so I didn't pick up type on 4
