### ISSUE TITLE
Trace error from blocking functions beforeUserCreatedFunc

### ISSUE THREAD

**Issue by lox** [firebase/firebase-functions#1471]
We've recently been seeing errors from our blocking functions:

```
Request has invalid method "undefined"
```

```
Error: Invalid request, unable to process
    at entryFromArgs (/workspace/node_modules/.pnpm/firebase-functions@4.4.1_firebase-admin@11.10.1/node_modules/firebase-functions/lib/logger/index.js:130:19)
    at Object.error (/workspace/node_modules/.pnpm/firebase-functions@4.4.1_firebase-admin@11.10.1/node_modules/firebase-functions/lib/logger/index.js:116:11)
    at /workspace/node_modules/.pnpm/firebase-functions@4.4.1_firebase-admin@11.10.1/node_modules/firebase-functions/lib/common/providers/identity.js:414:24
    at /workspace/node_modules/.pnpm/firebase-functions@4.4.1_firebase-admin@11.10.1/node_modules/firebase-functions/lib/v2/trace.js:16:28
    at /workspace/node_modules/.pnpm/@google-cloud+functions-framework@3.3.0/node_modules/@google-cloud/functions-framework/build/src/function_wrappers.js:146:25
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

```
DEFAULT 2023-10-17T01:11:55.128693Z TypeError: res.setHeader is not a function
DEFAULT 2023-10-17T01:11:55.128701Z at /workspace/node_modules/.pnpm/firebase-functions@4.4.1_firebase-admin@11.10.1/node_modules/firebase-functions/lib/common/providers/identity.js:462:17
DEFAULT 2023-10-17T01:11:55.128713Z at /workspace/node_modules/.pnpm/firebase-functions@4.4.1_firebase-admin@11.10.1/node_modules/firebase-functions/lib/v2/trace.js:16:28
DEFAULT 2023-10-17T01:11:55.128724Z at /workspace/node_modules/.pnpm/@google-cloud+functions-framework@3.3.0/node_modules/@google-cloud/functions-framework/build/src/function_wrappers.js:146:25
DEFAULT 2023-10-17T01:11:55.128733Z at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Looks like the common element in the stack traces is trace.js, could this be an error with trying to inject traces into blocking functions that don't have a response?

### [REQUIRED] Version info

**node:** 20.5.1

**firebase-functions:** 4.4.1

**firebase-tools:** 12.6.2

**firebase-admin:** 11.10.1

**Comment by lox** [comment]
Closing, this appears to be a `firebase-tools` issue: https://github.com/firebase/firebase-tools/issues/6414
