### ISSUE TITLE
Instructions for Parameterized Configuration are not clear about deployment issues.

### ISSUE THREAD

**Issue by timothywise-lhs** [firebase/firebase-functions#1505]
### [REQUIRED] Version info

**node:**
node v21.4.0

**firebase-functions:**
13.0.2

**firebase-tools:**

**firebase-admin:**

### [REQUIRED] Test case

```
const apikey = defineSecret("APIKEY");
runWith({
  secrets: [apikey.name],
});
export const loadRemoteInfo = onRequest({secrets: [apikey]}, async (request, response) => {
  try {
    const responseFromRemote = await axios.get("https://remoteapi.com/api/v3/endpoint?key="+apikey.value());
    const data = responseFromRemote.data;
    response.status(200).send(data);
  } catch (error) {
    console.error("Error making https request: ", error);
    response.status(500).send();
  }
});
```

### [REQUIRED] Steps to reproduce

Following the instructions at (https://firebase.google.com/docs/functions/config-env?gen=2nd#secret_parameters)
it gives instructions that one can use the secret in your typescript function, not really explaining the caveat about the secret not available at configuration and its implications.

### [REQUIRED] Expected behavior
Follow the instructions correctly, and it works.

### [REQUIRED] Actual behavior

First, the instructions don't mention that one must enable the Secrets product in GCP for your project.  Once that is done, the instructions also don't mention the page or a short command on how to set the secret `firebase functions:secrets:set` when deploying beyond the local emulator (which prompts for the secret).

Lastly, the storing secrets in via the instructions doesn't actually work and appears not supported because of the error:
`Error: Failed to load function definition from source: Failed to generate manifest from function source: Error: Cannot access the value of secret "APIKEY" during function deployment. Secret values are only available at runtime.`

So, if they're only available at runtime, how does one deploy a function at depends on them?  Is there an option that is required when running `npm run deploy` that should be in the linked document on using secret parameters?  If so, it should be readily apparent in link above on how to use secret parameters.  If not, the section on secret parameters should be omitted as functions that rely on them are non-deployable?

### Were you able to successfully deploy your functions?

no

**Comment by mr-jackpot** [comment]
@timothywise-lhs did you ever find a way around this? I'm experiencing the same issue after trying to configure a secret using `defineSecret()` in my firebase function.

**Comment by timothywise-lhs** [comment]
Unfortunately no.

**Comment by CorieW** [comment]
Hi @timothywise-lhs,

Thanks for reporting this issue! We’ve received it and are reviewing it. We’ll provide updates as soon as possible.

**Comment by maheshj01** [comment]
@CorieW Any updates on this, Here are the 

Steps to reproduce

1. create a secret `firebase functions:secrets:set RESEND_API_KEY`
2.  sample `functions/index.ts`

```ts
import * as admin from "firebase-admin";
import { defineSecret } from "firebase-functions/params";
import * as functions from "firebase-functions/v2";
import { Resend } from "resend";

// Initialize Firebase Admin
admin.initializeApp();

// Get Resend API key from environment variables
const resendApiKey = defineSecret("RESEND_API_KEY");
const resend = new Resend(resendApiKey.value());
console.log("Resend API Key:", resendApiKey.value());
if (!resendApiKey) {
  throw new Error("RESEND_API_KEY environment variable is not set");
}


export const onFeedbackCreated = functions.firestore.onDocumentCreated(
  "feedback/{documentId}",
  async (event) => {

}

});
```

3. Try to deploy the functions using `firebase deploy --only functions`

<details>
<summary>logs</summary>

```
mahesh@MacBook-Pro-81 functions % firebase deploy --only functions
(node:44965) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

=== Deploying to 'my-project'...

i  deploying functions
Running command: npm --prefix "$RESOURCE_DIR" run lint

> lint
> eslint --ext .js,.ts .

=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <5.2.0

YOUR TYPESCRIPT VERSION: 5.8.3

Please only submit bug reports when using the officially supported version.

Running command: npm --prefix "$RESOURCE_DIR" run build

> build
> tsc

✔  functions: Finished running predeploy script.
i  functions: preparing codebase default for deployment
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
i  artifactregistry: ensuring required API artifactregistry.googleapis.com is enabled...
✔  functions: required API cloudbuild.googleapis.com is enabled
✔  artifactregistry: required API artifactregistry.googleapis.com is enabled
✔  functions: required API cloudfunctions.googleapis.com is enabled
i  functions: Loading and analyzing source code for codebase default to determine what to deploy
Serving at port 8687

Error: Cannot access the value of secret "RESEND_API_KEY" during function deployment. Secret values are only available at runtime.
    at SecretParam.value (/Users/mahesh/Development/epoch/functions/node_modules/firebase-functions/lib/params/types.js:289:19)
    at Object.<anonymous> (/Users/mahesh/Development/epoch/functions/lib/index.js:45:49)
    at Module._compile (node:internal/modules/cjs/loader:1572:14)
    at Object..js (node:internal/modules/cjs/loader:1709:10)
    at Module.load (node:internal/modules/cjs/loader:1315:32)
    at Function._load (node:internal/modules/cjs/loader:1125:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:216:24)
    at Module.require (node:internal/modules/cjs/loader:1337:12)
    at require (node:internal/modules/helpers:139:16)


Error: Functions codebase could not be analyzed successfully. It may have a syntax or runtime error
mahesh@MacBook-Pro-81 functions % 
```
</details>

**Comment by CorieW** [comment]
@maheshj01 thanks for this.

I remember looking at this, I must have gotten sidetracked and forgot. I'll have a look at this again tomorrow.

**Comment by CorieW** [comment]
@timothywise-lhs your test case seems to work fine for me using the latest versions of things. I wonder if there had been an issue at some point in the past that has since been resolved. If you have the versions you used for `firebase-functions`, `firebase-tools`, and `firebase-admin`, I could investigate this further.

@maheshj01 yeah, I get the error here too. However, I believe this is intended. You'd probably have to do something like the following:
```js
import * as admin from "firebase-admin";
import { defineSecret } from "firebase-functions/params";
import * as functions from "firebase-functions/v2";
import { Resend } from "resend";

// Initialize Firebase Admin
admin.initializeApp();

const resendApiKey = defineSecret("RESEND_API_KEY");

export const onFeedbackCreated = functions.firestore.onDocumentCreated(
  { document: "feedback/{documentId}", secrets: [resendApiKey] },
  async (event) => {
    // Get Resend API key from environment variables
    console.log("Resend API Key:", resendApiKey.value());
    functions.logger.info("Resend API Key:", resendApiKey.value());
    if (!resendApiKey) {
      throw new Error("RESEND_API_KEY environment variable is not set");
    }
  })
```

**Comment by maheshj01** [comment]
Thanks @CorieW that worked.
