### ISSUE TITLE
TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Content-Disposition"]

### ISSUE THREAD

**Issue by dumitruPuggle** [firebase/firebase-functions#1514]
Hello, I'm having issues with firebase cloud functions. I have a simple callable function, which accepts requests, but for some reason when I call this from frontend in a emulator suite, then the emulators are killed with error code 

Here's the example:
```
$ firebase emulators:start
i  emulators: Starting emulators: auth, functions, firestore, storage
⚠  emulators: It seems that you are running multiple instances of the emulator suite for project viaterna. This may result in unexpected behavior.
⚠  functions: The following emulators are not running, calls to these services from the Functions emulator will affect production: database, hosting, pubsub
i  firestore: Firestore Emulator logging to firestore-debug.log
✔  firestore: Firestore Emulator UI websocket is running on 9150.
i  ui: Emulator UI logging to ui-debug.log
i  functions: Watching "/Users/dumitrucucu/Desktop/VRSEN/viaterna/functions" for Cloud Functions...
✔  functions: Using node@18 from host.
i  functions: Loaded environment variables from .env.
Serving at port 8659

✔  functions: Loaded functions definitions from source: authOnCreate, authOnDelete, getResponse, createAvatar, getAvatars, updateAvatar, onCloneComplete.
✔  functions[us-central1-authOnCreate]: auth function initialized.
✔  functions[us-central1-authOnDelete]: auth function initialized.
✔  functions[us-central1-getResponse]: http function initialized (http://127.0.0.1:5001/viaterna/us-central1/getResponse).
✔  functions[us-central1-createAvatar]: http function initialized (http://127.0.0.1:5001/viaterna/us-central1/createAvatar).
✔  functions[us-central1-getAvatars]: http function initialized (http://127.0.0.1:5001/viaterna/us-central1/getAvatars).
✔  functions[us-central1-updateAvatar]: http function initialized (http://127.0.0.1:5001/viaterna/us-central1/updateAvatar).
✔  functions[us-central1-onCloneComplete]: http function initialized (http://127.0.0.1:5001/viaterna/us-central1/onCloneComplete).

┌─────────────────────────────────────────────────────────────┐
│ ✔  All emulators ready! It is now safe to connect your app. │
│ i  View Emulator UI at http://127.0.0.1:4000/               │
└─────────────────────────────────────────────────────────────┘

┌────────────────┬────────────────┬─────────────────────────────────┐
│ Emulator       │ Host:Port      │ View in Emulator UI             │
├────────────────┼────────────────┼─────────────────────────────────┤
│ Authentication │ 127.0.0.1:9099 │ http://127.0.0.1:4000/auth      │
├────────────────┼────────────────┼─────────────────────────────────┤
│ Functions      │ 127.0.0.1:5001 │ http://127.0.0.1:4000/functions │
├────────────────┼────────────────┼─────────────────────────────────┤
│ Firestore      │ 127.0.0.1:8080 │ http://127.0.0.1:4000/firestore │
├────────────────┼────────────────┼─────────────────────────────────┤
│ Storage        │ 127.0.0.1:9199 │ http://127.0.0.1:4000/storage   │
└────────────────┴────────────────┴─────────────────────────────────┘
  Emulator Hub running at 127.0.0.1:4400
  Other reserved ports: 4500, 9150

Issues? Report them at https://github.com/firebase/firebase-tools/issues and attach the *-debug.log files.
 
i  functions: Loaded environment variables from .env.
i  functions: Beginning execution of "us-central1-createAvatar"
i  functions: Finished "us-central1-createAvatar" in 4.491417ms
i  functions: Beginning execution of "us-central1-createAvatar"
>  {"verifications":{"app":"VALID","auth":"VALID"},"logging.googleapis.com/labels":{"firebase-log-type":"callable-request-verification"},"severity":"DEBUG","message":"Callable request verification passed"}

Error: An unexpected error has occurred.

Having trouble? Try again or contact support with contents of firebase-debug.log
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
dumitrucucu@Dumitrus-Mac-mini functions % 
```

(firebase-debug.log):
``` 
[debug] [2024-01-18T21:54:43.975Z] Accepted request POST /viaterna/us-central1/createAvatar --> us-central1-createAvatar
[debug] [2024-01-18T21:54:43.977Z] [functions] Runtime ready! Sending request! {"metadata":{"emulator":{"name":"functions"},"message":"[functions] Runtime ready! Sending request!"}}
[debug] [2024-01-18T21:54:43.977Z] [functions] Got req.url=/viaterna/us-central1/createAvatar, mapping to path=/ {"metadata":{"emulator":{"name":"functions"},"message":"[functions] Got req.url=/viaterna/us-central1/createAvatar, mapping to path=/"}}
[debug] [2024-01-18T21:54:43.978Z] [worker-pool] submitRequest(triggerId=us-central1-createAvatar) {"metadata":{"emulator":{"name":"functions"},"message":"[worker-pool] submitRequest(triggerId=us-central1-createAvatar)"}}
[info] i  functions: Beginning execution of "us-central1-createAvatar" {"metadata":{"emulator":{"name":"functions"},"function":{"name":"us-central1-createAvatar"},"extension":{},"message":"Beginning execution of \"us-central1-createAvatar\""}}
[debug] [2024-01-18T21:54:43.978Z] [worker-us-central1-createAvatar-4eaad083-4b2e-4b0a-8356-23d8e645f644]: BUSY {"metadata":{"emulator":{"name":"functions"},"function":{"name":"us-central1-createAvatar"},"extension":{},"message":"[worker-us-central1-createAvatar-4eaad083-4b2e-4b0a-8356-23d8e645f644]: BUSY"}}
[info] >  {"verifications":{"app":"VALID","auth":"VALID"},"logging.googleapis.com/labels":{"firebase-log-type":"callable-request-verification"},"severity":"DEBUG","message":"Callable request verification passed"} {"user":{"verifications":{"app":"VALID","auth":"VALID"},"logging.googleapis.com/labels":{"firebase-log-type":"callable-request-verification"},"severity":"DEBUG","message":"Callable request verification passed"},"metadata":{"emulator":{"name":"functions"},"function":{"name":"us-central1-createAvatar"},"extension":{},"message":"\u001b[90m> \u001b[39m {\"verifications\":{\"app\":\"VALID\",\"auth\":\"VALID\"},\"logging.googleapis.com/labels\":{\"firebase-log-type\":\"callable-request-verification\"},\"severity\":\"DEBUG\",\"message\":\"Callable request verification passed\"}"}}
[debug] [2024-01-18T21:54:44.231Z] Jan 18, 2024 11:54:44 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected HTTP/2 connection.
 {"metadata":{"emulator":{"name":"firestore"},"message":"Jan 18, 2024 11:54:44 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead\nINFO: Detected HTTP/2 connection.\n"}}
  [debug] [2024-01-18T21:54:44.426Z] TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Content-Disposition"]
      at ServerResponse.setHeader (node:_http_outgoing:606:3)
      at sendFileBytes (/Users/dumitrucucu/.cache/firebase/tools/lib/node_modules/firebase-tools/lib/emulator/storage/apis/shared.js:19:9)
      at /Users/dumitrucucu/.cache/firebase/tools/lib/node_modules/firebase-tools/lib/emulator/storage/apis/gcloud.js:88:47
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[error] 
[error] Error: An unexpected error has occurred.

``` 
The worst part is, that this kills the emulators with:
```
error Command failed with exit code 2.
```

### [REQUIRED] Version info

**node:**: 18.17.1

**firebase-functions:**: ^4.6.0

**firebase-tools:**

**firebase-admin:**: ^11.11.0

### [REQUIRED] Steps to reproduce

1. Create a callable function with app check
2. Call it from frontend under the firebase emulator suite environment

### [REQUIRED] Expected behavior

Not to kill the emulators without explaining why. And I suppose that this shouldn't fail in general.

### Were you able to successfully deploy your functions?

Yes, I was able to deploy the functions! They work in production, however the emulators don't.

Thank you!

**Comment by exaby73** [comment]
Hello @dumitruPuggle. Could you please provide a code sample so that I may test it myself as well? Also I see you you haven't provided information about the version of `firebase-tools` you're using. Please provide that as well. This would be the version of the Firebase CLI you can get by running `firebase --version`

**Comment by apeiniger** [comment]
@dumitruPuggle Did you figure out what the problem is because I'm experienced the same currently?
