### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'seconds')

### ISSUE THREAD

**Issue by magelikescoke** [firebase/firebase-functions#1526]
[REQUIRED] Version info
node: v20.9.0

firebase-functions: 4.4.1

firebase-admin: 11.11.0

**Comment by magelikescoke** [comment]
```
TypeError: Cannot read properties of null (reading 'seconds')
    at Timestamp.fromProto (/workspace/node_modules/@google-cloud/firestore/build/src/timestamp.js:145:47)
    at Transform.transform [as _transform] (/workspace/node_modules/@google-cloud/firestore/build/src/reference.js:1946:56)
    at Transform._write (node:internal/streams/transform:171:8)
    at writeOrBuffer (node:internal/streams/writable:564:12)
    at _write (node:internal/streams/writable:493:10)
    at Writable.write (node:internal/streams/writable:502:10)
    at PassThrough.ondata (node:internal/streams/readable:1007:22)
    at PassThrough.emit (node:events:518:28)
    at PassThrough.emit (node:domain:551:15)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushObjectMode (node:internal/streams/readable:536:3)
    at Readable.push (node:internal/streams/readable:391:5)
    at node:internal/streams/transform:178:12
    at PassThrough._transform (node:internal/streams/passthrough:46:3)
```

**Comment by magelikescoke** [comment]
This is the stacktrace that I get:

**Comment by magelikescoke** [comment]
Related issue #922

**Comment by jjnistico** [comment]
Same here but our stacktrace looks like 

`TypeError: Cannot read properties of null (reading 'seconds')
    at Function.fromProto (/layers/google.nodejs.yarn/yarn_modules/node_modules/@google-cloud/firestore/build/src/timestamp.js:145:47)
    at Transform.transform [as _transform] (/layers/google.nodejs.yarn/yarn_modules/node_modules/@google-cloud/firestore/build/src/reference.js:1946:56)
    at Transform._write (node:internal/streams/transform:175:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Transform.Writable.write (node:internal/streams/writable:337:10)
    at PassThrough.ondata (node:internal/streams/readable:809:22)
    at PassThrough.emit (node:events:517:28)
    at PassThrough.emit (node:domain:552:15)
    at addChunk (node:internal/streams/readable:368:12)`

**Comment by gowtham-10729404** [comment]
> Related issue #922

But that was "Cannot read properties of undefined (reading 'seconds')" but its now "TypeError: Cannot read properties of null (reading 'seconds')"

@google-cloud/firestore : 7.1.0

**Comment by jjnistico** [comment]
> > Related issue #922
> 
> But that was "Cannot read properties of undefined (reading 'seconds')" but its now "TypeError: Cannot read properties of null (reading 'seconds')"
> 
> @google-cloud/firestore : 7.1.0

I've had both over the past week or two

**Comment by inlined** [comment]
Sorry for the delay; I'm not sure why this fell through the cracks.

This is occurring in Cloud Functions, but is either a regression in the @google-cloud/firestore SDK or the Firestore backend. I'm looping in the appropriate teams to diagnose internally.

**Comment by jjnistico** [comment]
> Sorry for the delay; I'm not sure why this fell through the cracks.
> 
> This is occurring in Cloud Functions, but is either a regression in the @google-cloud/firestore SDK or the Firestore backend. I'm looping in the appropriate teams to diagnose internally.

Thank you!

Just to give a bit more info, I've resolved this by changing my reads. I had some cloud functions that red large collections of documents and ran some aggregations on the data. In one case it seemed like contention on the collection was causing issues but for another, no such thing. However, it never occurred on small collections. The one that was causing this error had ~110k documents which would be read in its entirety.

**Comment by inlined** [comment]
Can someone who is reproducing help me by checking your npm lockfile and telling me which version of `@google-cloud/firestore` you're using? In the versions I'm debugging, `build/src/reference.js:1946` isn't the function in the stack trace (and has nothing to do with parsing)

**Comment by inlined** [comment]
> Just to give a bit more info, I've resolved this by changing my reads.

Oh, this is happening when you're reading in your application, not in the boilerplate before your code gets called? I may have been thrown off by the root cause of the old issue that was linked. A minimal reproduction could help me debug this faster.

**Comment by jjnistico** [comment]
> > Just to give a bit more info, I've resolved this by changing my reads.
> 
> Oh, this is happening when you're reading in your application, not in the boilerplate before your code gets called? I may have been thrown off by the root cause of the old issue that was linked. A minimal reproduction could help me debug this faster.

Yes this is happening from reads only. `@google-cloud/firestore: 6.8.0`.

Unfortunately can't repro anything simple because it seems dependent on the size of the collection but here is where the error was thrown

```
await admin
        .firestore()
        .collection("path/to/collection")
        .get()
        .then(
          (res) =>  res.docs
        )
```

**Comment by magelikescoke** [comment]
> because it seems dependent on the size of the collection but here is where the error was thrown

the same `@google-cloud/firestore: 6.8.0`
Unfortunately I can not distinguish whether it is crashed when reading or writing. It seems to occur in stream, and can not be catched. I'm not sure when it happened.

**Comment by inlined** [comment]
But to confirm, both of your functions are starting correctly, yet when you use Firestore within your functions you get an exception? If this is the case, I'll move the issue over to the repo for the Firestore SDK to make sure the appropriate team gets assigned (we only make the firebase-functions SDK and portions of firebase-tools, not all possible SDKs you can interact with from within a Cloud Function)

**Comment by inlined** [comment]
Generally speaking, Google only makes linear updates (e.g. we wouldn't release 6.8.1 now that 7.3.1 is out). Since this doesn't seem to be reproducing in the latest SDKs, please update to the latest version of the SDK and reopen the bug if the problem persists.
