### ISSUE TITLE
TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by PietechSolution** [firebase/firebase-functions#186]
node -v 8.9.4
npm -v 5.6.0
************code************************
 const functions = require('firebase-functions');
var serviceAccount = require("./serviceAccount.json");
var admin = require("firebase-admin");
admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  databaseURL: "https://firestoredemo3.firebaseio.com"
});
var db = admin.firestore();
const http=require('http');
const express=require('express');
var app=express();
var server=http.createServer(app);
const port=process.env.PORT || 2500;
exports.myFunctionName = functions.firestore
  .document("users/alovelace").onWrite((event) => {
    console.log('helo world')
  });

server.listen(port , ()=> {
  console.log(`server is up on port ${port}`)
})
:*****************************error**********************************
D:\officeproject\new\cloudfunctionProject\firestoredemo3\functions>nodemon index.js
[nodemon] 1.14.12
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node index.js`
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:1246:7)
    at database (D:\officeproject\new\cloudfunctionProject\firestoredemo3\functions\node_modules\firebase-functions\lib\providers\firestore.js:36:45)
    at Object.document (D:\officeproject\new\cloudfunctionProject\firestoredemo3\functions\node_modules\firebase-functions\lib\providers\firestore.js:44:12)
    at Object.<anonymous> (D:\officeproject\new\cloudfunctionProject\firestoredemo3\functions\index.js:30:4)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)

**Comment by laurenzlong** [comment]
Closing because not following issues template.
