### ISSUE TITLE
Add support for handling malformed JSON body

### ISSUE THREAD

**Issue by richarddd** [firebase/firebase-functions#190]
### Version info

**firebase-cli:**
3.17.4

**firebase-functions:**
0.8.1

**firebase-tools:**
3.16.0

**firebase-admin:**
5.8.1

### Test case

Send a malformed JSON to any request.

### Steps to reproduce

Send a malformed JSON to any request:
```
{
  "userId" : "190101014801",
  "pin : "12312"
}
```

### Were you able to successfully deploy your functions?

Yes

### Expected behavior

My express error handling middleware should be able to handle the error. Or at lest the server should send an error response and not timeout after  `execution attempt timed out`

### Actual behavior

Firebase logs the error to console log, then request timeouts and sends:

```
"error":{
"code": 500,
"status": "INTERNAL",
"message": "function execution attempt timed out"
}
```

Log message:
```
error: { SyntaxError: Unexpected number in JSON at position 39
    at Object.parse (native)
    at parse (/Users/richard/.config/yarn/global/node_modules/body-parser/lib/types/json.js:88:17)
    at /Users/richard/.config/yarn/global/node_modules/body-parser/lib/read.js:116:18
    at invokeCallback (/Users/richard/.config/yarn/global/node_modules/raw-body/index.js:262:16)
    at done (/Users/richard/.config/yarn/global/node_modules/raw-body/index.js:251:7)
    at IncomingMessage.onEnd (/Users/richard/.config/yarn/global/node_modules/raw-body/index.js:307:7)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  body: '{\n\t"userId" : "190101014801",\n  "pin: "12312"\n}',
  status: 400,
  statusCode: 400 }
```

**Comment by laurenzlong** [comment]
I'm assuming you are using HTTPS onRequest functions. If you do want error checking for JSON, then consider using [HTTPS onCall functions](https://firebase.google.com/docs/functions/callable). 

If you would like to file a request to return a different HTTP response code for onRequest functions, please file a ticket in the Google Cloud Functions public tracker: https://cloud.google.com/support/docs/issue-trackers
