### ISSUE TITLE
Error while acquiring application default credentials

### ISSUE THREAD

**Issue by AndreasHald** [firebase/firebase-functions#204]
### Version info

**firebase-functions:**
0.8.2

**firebase-tools:**
5.6.0

**firebase-admin:**
5.10.0

### Test case

```
import * as functions from 'firebase-functions';
admin.initializeApp(functions.config().firebase);
```

### Steps to reproduce
Deploy the app to firestore

### Were you able to successfully deploy your functions?
I successfully deploy every time to firestore, the error only occurs when a function is running.

### Expected behavior
Expected no error when functions are running.

### Actual behavior
When the functions run i get the following error message in the firebase log: 
```
Error: Unexpected error while acquiring application default credentials: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
    at GoogleAuth.<anonymous> (/user_code/node_modules/firebase-admin/node_modules/google-auth-library/build/src/auth/googleauth.js:229:31)
    at step (/user_code/node_modules/firebase-admin/node_modules/google-auth-library/build/src/auth/googleauth.js:47:23)
    at Object.next (/user_code/node_modules/firebase-admin/node_modules/google-auth-library/build/src/auth/googleauth.js:28:53)
    at fulfilled (/user_code/node_modules/firebase-admin/node_modules/google-auth-library/build/src/auth/googleauth.js:19:58)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```

**Comment by laurenzlong** [comment]
Please file support ticket: firebase.google.com/support

**Comment by TimeTravelersHackedMe** [comment]
did you end filing a ticket? I'm having the same problem

**Comment by jamesmgg** [comment]
+1

**Comment by sdathth** [comment]
@laurenzlong      laurenzlong closed this on Mar 19 but i still see the problem. In fact i get a lot of them. It is not like every calls fails but some calls fails more often than others!
