### ISSUE TITLE
'functions:config:unset' Fails When Specifying More Than One Key

### ISSUE THREAD

**Issue by samcaplat** [firebase/firebase-functions#245]
### Version info

**firebase-functions:** ^1.0.2

**firebase-tools:** 3.18.2

**firebase-admin:** 5.12.0

### Steps to reproduce

Running CLI command as per the docs: `firebase functions:config:unset name.first_key, name.second_key, name.third_key`

Command in docs appears as: `firebase functions:config:unset key1, key2`

### Actual behavior

Command fails with `Error: An unexpected error has occurred.`

Logs (have been edited slightly for privacy):

```text
 Thu May 17 2018 15:46:06 GMT+0100 (GMT Summer Time)
[debug] [2018-05-17T14:46:06.366Z] <<< HTTP RESPONSE 404
[debug] [2018-05-17T14:46:06.366Z] <<< HTTP RESPONSE BODY <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/v1beta1/projects/{name_of_project}/configs/</code> was not found on this server.  <ins>That’s all we know.</ins>

[debug] [2018-05-17T14:46:06.368Z] TypeError: Cannot create property 'error' on string '<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/v1beta1/projects/{name_of_project}/configs/</code> was not found on this server.  <ins>That’s all we know.</ins>
'
    at module.exports (C:\Users\SAMCAP~1\AppData\Roaming\npm\node_modules\firebase-tools\lib\responseToError.js:11:16)
    at Request._callback (C:\Users\SAMCAP~1\AppData\Roaming\npm\node_modules\firebase-tools\lib\api.js:45:25)
    at Request.self.callback (C:\Users\SAMCAP~1\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:186:22)
    at Request.emit (events.js:127:13)
    at Request.emit (domain.js:421:20)
    at Request.<anonymous> (C:\Users\SAMCAP~1\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:1163:10)
    at Request.emit (events.js:127:13)
    at Request.emit (domain.js:421:20)
    at IncomingMessage.<anonymous> (C:\Users\SAMCAP~1\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:219:13)
[error] 
[error] Error: An unexpected error has occurred.
```

The `.firebaserc` file displays the same project name that is included in the logs. I've removed this for privacy and replaced it with `{name_of_project}`

At the moment I'm removing environment variables one at a time, that works as expected.

Thanks,
Sam

**Comment by laurenzlong** [comment]
Remove the space between the two keys.
