### ISSUE TITLE
Functions deploy assume all modules packaged when only part of node_modules are ignored 

### ISSUE THREAD

**Issue by vincentlaucy** [firebase/firebase-functions#249]
### Version info

**firebase-functions:**
1.0.3
**firebase-tools:**
3.18.5
**firebase-admin:**
 5.12.1
### Test case

Deploy Firebase functions

### Steps to reproduce

in Firebase.json, use regex to selectively ignore particular module
e.g. `"**/node_modules/!(mymodule)**"`

### Were you able to successfully deploy your functions?

Yes when I ignore all modules i.e. `"**/node_modules/**"`

### Expected behavior

Fetch all modules per package.json, except those already packaged (`mymodule`) under node_modules

### Actual behavior

Error showing irrelevant modules (e.g. lodash) not found, which is already specified in package.json

**Comment by laurenzlong** [comment]
Can you actually copy the full log you get when you run the command with --debug?

**Comment by vincentlaucy** [comment]
➜  functions-es6 git:(chatbot-functions) ✗ firebase deploy --only functions
=== Deploying to '**************'...

i  deploying functions
i  functions: ensuring necessary APIs are enabled...
✔  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...
i  functions: packaged functions (615.6 KB) for uploading
✔  functions: functions folder uploaded successfully
i  functions: updating function **************...
⚠  functions[**************]: Deployment error.
Function load error: Code in file index.js can't be loaded.
Did you list all required modules in the package.json dependencies?
Detailed stack trace: Error: Cannot find module 'firebase-functions'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/user_code/index.js:3:41)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)

(Double checked it's in package.json, and installed under node_modules)

This happen when the ignore is `"**/node_modules/!(mymodule)**"`, but no problem with `"**/node_modules/**"`

**Comment by thechenky** [comment]
@vincentlaucy are you still having this issue? Please make sure you're using the latest firebase-functions and firebase-tools versions.

**Comment by vincentlaucy** [comment]
yes with latest firebase-tools `6.1.1` & firebase-functions `2.1.0`

seems the validations of modules inside package.json happen after archive? I can't find validation part of code in `firebase-tools`.
So I always end up either file too large (including node_modules) or failed in validations (firebase-funcitons misisng etc)

**Comment by thechenky** [comment]
Hi @vincentlaucy thanks for the update. Can you paste your full `package.json` file from the functions directory? Also, how large is the code in your index.js?

**Comment by thechenky** [comment]
Closing due to inactivity.
