### ISSUE TITLE
db.collection().doc().update() doen't update the firestore document

### ISSUE THREAD

**Issue by prakashsellathurai** [firebase/firebase-functions#261]
Error: Invalid use of type "undefined" as a Firestore argument.
    at Object.exports.customObjectError.val [as customObjectError] (/user_code/node_modules/firebase-admin/node_modules/@google-cloud/firestore/src/validate.js:164:14)
    at Function.encodeValue (/user_code/node_modules/firebase-admin/node_modules/@google-cloud/firestore/src/document.js:813:20)
    at merge (/user_code/node_modules/firebase-admin/node_modules/@google-cloud/firestore/src/document.js:253:45)
    at merge (/user_code/node_modules/fire

**Comment by laurenzlong** [comment]
Please follow the issue template.
