### ISSUE TITLE
functions.auth.UserRecord.toJSON() does not return valid JSON

### ISSUE THREAD

**Issue by timothegenzmer** [firebase/firebase-functions#270]
### Version info

**firebase-functions:** 1.04

**firebase-tools:** 3.18.5

**firebase-admin:** 5.12.1

### Test case
```
const functions = require("firebase-functions");
const admin = require("firebase-admin");

admin.initializeApp();

exports.userAuth = functions.auth.user().onCreate(userRecord => admin.database().ref(`/USER_RECORD/${userRecord.uid}`).set(userRecord.toJSON()));
```

### Steps to reproduce

deploy given example
create new user

### Were you able to successfully deploy your functions?

yes

### Expected behavior

userRecord.toJSON() returns a valid JSON

### Actual behavior

object returned by userRecord.toJSON() contains functions.

most likely this is caused by:
firebase-functions/lib/providers/auth.js:111
```
    _.forEach(record.providerData, entry => {
        _.set(entry, 'toJSON', () => {
            return entry;
        });
    });
```
_toJSON_ returns _this_ instead of JSON

Stacktrace:
```
Error: Reference.set failed: First argument contains a function in property '${path}.${userRecord.uid}.providerData.0.toJSON' with contents = () => { return entry; }

        at validateFirebaseData (/user_code/node_modules/firebase-admin/node_modules/@firebase/database/dist/index.node.cjs.js:1436)
        at (/user_code/node_modules/firebase-admin/node_modules/@firebase/database/dist/index.node.cjs.js:1479)
        at Object.forEach (/user_code/node_modules/firebase-admin/node_modules/@firebase/database/node_modules/@firebase/util/dist/index.node.cjs.js:835)
        at validateFirebaseData (/user_code/node_modules/firebase-admin/node_modules/@firebase/database/dist/index.node.cjs.js:1462)
        at (/user_code/node_modules/firebase-admin/node_modules/@firebase/database/dist/index.node.cjs.js:1479)
        at Object.forEach (/user_code/node_modules/firebase-admin/node_modules/@firebase/database/node_modules/@firebase/util/dist/index.node.cjs.js:835)
        at validateFirebaseData (/user_code/node_modules/firebase-admin/node_modules/@firebase/database/dist/index.node.cjs.js:1462)
        at (/user_code/node_modules/firebase-admin/node_modules/@firebase/database/dist/index.node.cjs.js:1479)
        at Object.forEach (/user_code/node_modules/firebase-admin/node_modules/@firebase/database/node_modules/@firebase/util/dist/index.node.cjs.js:835)
        at validateFirebaseData (/user_code/node_modules/firebase-admin/node_modules/@firebase/database/dist/index.node.cjs.js:1462)
        at validateFirebaseDataArg (/user_code/node_modules/firebase-admin/node_modules/@firebase/database/dist/index.node.cjs.js:1421)
        at Reference.set (/user_code/node_modules/firebase-admin/node_modules/@firebase/database/dist/index.node.cjs.js:13963)
        at * (/user_code/*.js:12)
        at * (/user_code/*.js:34)
        at * (*.js:45)
        at Object.<anonymous> (/user_code/node_modules/firebase-functions/lib/cloud-functions.js:112)

```

**Comment by laurenzlong** [comment]
This is indeed a bug. However, what if you used `userRecord` itself instead of `userRecord.toJSON()`? I believe it is already a valid JSON.

**Comment by thechenky** [comment]
Internal bug reference: 110432691

**Comment by thechenky** [comment]
@timothegenzmer is this issue still happening for you?

**Comment by thechenky** [comment]
I was able to reproduce this - will be adding a fix soon. Thanks!

**Comment by pariola** [comment]
Still facing the same issue!

**Comment by Carduelis** [comment]
Yep. The same. I was trying `userRecord.toJSON()` - no luck. Later, I decided to write it attribute by attribute. `metadata.toJSON()` was fine, but `providerData: userRecord.providerData.map(item => item.toJSON()),` is failing,
```
TypeError: userRecord.providerData.toJSON is not a function
```
From the [docs](https://firebase.google.com/docs/reference/admin/node/admin.auth.UserRecord)
providerData
non-null Array of non-null [admin.auth.UserInfo](https://firebase.google.com/docs/reference/admin/node/admin.auth.UserInfo) which is should have a `toJSON()`-method, but it turns out in Error:
```
Error: Input is not a plain JavaScript object.
    at Object.customObjectError (/user_code/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/validate.js:162:15)
    at Serializer.encodeValue (/user_code/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/serializer.js:142:26)
    at Serializer.encodeFields (/user_code/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/serializer.js:50:34)
    at Serializer.encodeValue (/user_code/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/serializer.js:135:44)
    at Serializer.encodeValue (/user_code/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/serializer.js:120:38)
    at Serializer.encodeFields (/user_code/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/serializer.js:50:34)
    at Function.fromObject (/user_code/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/document.js:96:53)
    at WriteBatch.set (/user_code/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/write-batch.js:238:54)
    at DocumentReference.set (/user_code/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/reference.js:340:27)
    at createProfile (/user_code/auth/createUserProfile.js:17:6)
```

**Comment by pariola** [comment]
try `JSON.parse(JSON.stringify(record));`

**Comment by thechenky** [comment]
Hi @pariola and @Carduelis thanks for chiming in - this issue slipped through the cracks, but we're still planning to put in a fix. In the meantime, please use the workaround mentioned in https://github.com/firebase/firebase-functions/issues/270#issuecomment-457759775

**Comment by psdewar2** [comment]
JSON.parse(JSON.stringify(record)); doesn't work for me either. Any other options here?

**Comment by dsl101** [comment]
@joehan you marked this as fixed, but I'm still seeing it in firestore `onCreate()` / `onUpdate()` triggers, both when using the emulators and deployed to a cloud project.

@psdewar2 the JSON parse / stringify worked for me—will need a bit more detail to help you

For clarity, this is my code, stripped out from a much larger function:
```js

exports = module.exports = functions.firestore.document('/registrationLinks/{linkId}').onCreate(async snapshot => {

  const email = snapshot.data()?.['data']?.['email']  // This gets the email address from the created document

  if (email) {
    const userRecord = await admin.auth().getUserByEmail(email)  // Removed error handling for clarity
    return admin.firestore().collection('registrationLinks').doc(snapshot.id).update({
      existingAccount: userRecord                                      // Fails with error below
      // existingAccount: JSON.parse(JSON.stringify(userRecord))       // Works
    })
  }
})
```

which fails with this:
```
Error: Update() requires either a single JavaScript object or an alternating list of field/value pairs that can be followed by an optional precondition. Value for argument "dataOrField" is not a valid Firestore document. Couldn't serialize object of type "UserRecord" (found in field "existingAccount"). Firestore doesn't support JavaScript objects with custom prototypes (i.e. objects that were created via the "new" operator).
    at WriteBatch.update ([snip]\Firebase\functions\node_modules\@google-cloud\firestore\build\src\write-batch.js:378:23)
    at DocumentReference.update ([snip]\Firebase\functions\node_modules\@google-cloud\firestore\build\src\reference.js:392:14)
    at [snip]\Firebase\functions\firestore\registrationLinks\onCreate.f.js:21:65
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async runFunction ([snip]\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:564:9)
    at async runBackground ([snip]\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:576:5)
    at async processBackground ([snip]\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:559:5)
    at async invokeTrigger ([snip]\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:640:13)
    at async handleMessage ([snip]\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:742:9)
```

Switching the offending line to use the JSON parse / stringify pair works as expected.

Digging deeper, it does appear it's the `UserInfo` object that's the root cause.

**Comment by dsl101** [comment]
I know this is really old now, and not sure if it's just got lost, but I _think_ the problem is that the `UserInfo` `.toJSON()` function just returns all the keys / values, which includes any that are `undefined` (e.g. `{ phoneNumber: undefined }`). The `.stringify()` / `.parse()` trick removes any undefined values, to comply properly with the JSON specification, which [does not allow `undefined`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#description).

If the lower layer used `null` instead of `undefined` for missing information, it's likely the `.toJSON()` method would work, as that is a valid JSON value. So, probably best to stick with the workaround.
