### ISSUE TITLE
 Can't determine Firebase Database URL.

### ISSUE THREAD

**Issue by xpsdeset** [firebase/firebase-functions#277]
Suddenly I get this  when my functions are triggered. My functions which I deployed till last week were fine but when I deployed it today out of nowhere. 

> Can't determine Firebase Database URL.

This only happens for newly deployed functions. Not for the exciting onces. I updated functions, tools and admin packages but no luck. This doesn't happen on my shell only on firebase servers.   

### Version info

**firebase-functions:** ^1.1.0

**firebase-tools:** 3.19.3

**firebase-admin:** ^5.12.1

### Steps to reproduce

I have used below to initialize my firebase admin 
 
> admin.initializeApp()

### Were you able to successfully deploy your functions?

Deploys were successful 

### Actual behavior

Error: Can't determine Firebase Database URL.
    at FirebaseDatabaseError.Error (native)
    at FirebaseDatabaseError.FirebaseError [as constructor] (/user_code/node_modules/firebase-admin/lib/utils/error.js:39:28)
    at new FirebaseDatabaseError (/user_code/node_modules/firebase-admin/lib/utils/error.js:190:23)
    at DatabaseService.ensureUrl (/user_code/node_modules/firebase-admin/lib/database/database.js:75:15)
    at DatabaseService.getDatabase (/user_code/node_modules/firebase-admin/lib/database/database.js:52:26)
    at FirebaseApp.database (/user_code/node_modules/firebase-admin/lib/firebase-app.js:231:24)
    at FirebaseNamespace.fn (/user_code/node_modules/firebase-admin/lib/firebase-namespace.js:280:45)
    at /user_code/dist/chatRequest/index.js:15:29
    at next (native)
    at step (/user_code/dist/chatRequest/index.js:47:191)

**Comment by laurenzlong** [comment]
Where are you seeing this message? In your functions logs on the Firebase Console? Or locally? And do you have more than one database for this project?

**Comment by laurenzlong** [comment]
Can you try printing FIREBASE_CONFIG in your functions code? Does it have a databaseURL field?

Add this to your source code and deploy:

```
console.log(process.env.FIREBASE_CONFIG)
```

**Comment by JuniaYulia** [comment]
@laurenzlong I am also having the same issue. I am using two database for this project. 

const functions = require('firebase-functions');
const admin = require('firebase-admin');

var serviceAccount = require(__dirname + "/private/connectToFirebaseCloudFunction");

// default app database
admin.initializeApp({
    credential: admin.credential.cert(serviceAccount),
    databaseURL: "https://asap-expert1.firebaseio.com"
});

var consumerServiceAccount = require(__dirname + "/private/consumerServiceKey");

// secondary app database
var consumerAppConfig = {
    credential: admin.credential.cert(consumerServiceAccount),
    databaseURL: "https://asap-consumer.firebaseio.com"
};

var consumerApp = admin.initializeApp({
    consumerAppConfig
}, "secondary");


The error I'm getting is this: Error: Can't determine Firebase Database URL.
    at FirebaseDatabaseError.Error (native)
    at FirebaseDatabaseError.FirebaseError [as constructor] (/user_code/node_modules/firebase-admin/lib/utils/error.js:39:28)
    at new FirebaseDatabaseError (/user_code/node_modules/firebase-admin/lib/utils/error.js:190:23)
    at DatabaseService.ensureUrl (/user_code/node_modules/firebase-admin/lib/database/database.js:75:15)
    at DatabaseService.getDatabase (/user_code/node_modules/firebase-admin/lib/database/database.js:52:26)
    at FirebaseApp.database (/user_code/node_modules/firebase-admin/lib/firebase-app.js:231:24)
    at admin.auth.createUser.then (/user_code/index.js:95:53)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
  errorInfo: 
   { code: 'database/invalid-argument',
     message: 'Can\'t determine Firebase Database URL.' } }

**Comment by laurenzlong** [comment]
@JuniaYulia Could you file an issue in https://github.com/firebase/firebase-admin-node?
