### ISSUE TITLE
TypeError: firestoreInstance.settings is not a function

### ISSUE THREAD

**Issue by dauledk** [firebase/firebase-functions#295]
### Version info

**firebase-functions:**
2.0.2
**firebase-tools:**
4.0.1
**firebase-admin:**
5.12.1

### Test case
I am not sure. Happen's before any of my code executes

### Steps to reproduce
Deploy functions, and provoke a firestore trigger.

### Were you able to successfully deploy your functions?
yes

### Expected behavior
"Normal" executions of firestore triggers

### Actual behavior
This error in the console:
```javascript
TypeError: firestoreInstance.settings is not a function
    at beforeSnapshotConstructor (/srv/node_modules/firebase-functions/lib/providers/firestore.js:136:27)
    at changeConstructor (/srv/node_modules/firebase-functions/lib/providers/firestore.js:144:49)
    at cloudFunctionNewSignature (/srv/node_modules/firebase-functions/lib/cloud-functions.js:108:28)
    at /worker/worker.js:726:24
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

![screen shot 2018-07-31 at 17 01 07](https://user-images.githubusercontent.com/9967422/43468052-56f0dd46-94e3-11e8-97da-1d7c22fcb38d.png)

**Comment by amirhmk** [comment]
This gets rid of the type warning for that, but `settings` is a `void` function whereas `firebase()` returned a `Firebase` object and that's what my cloud functions are expecting. What is the correct behaviour here?

**Comment by felipeblini** [comment]
I am getting the same error, I've downgraded the firebase-admin to 5.13.0 and still not working

**Comment by laurenzlong** [comment]
@amirhmk I'm not sure what you mean, could you elaborate further? @felipeblini Do you have firebase-functions v2?

**Comment by putraxor** [comment]
even firebase-admin 6.0.0 still not working

**Comment by laurenzlong** [comment]
@putraxor Did you run "npm i" locally on your machine? You'll need to do this if you were manually editing package.json.
