### ISSUE TITLE
Error occurred while parsing your function triggers. Unexpected token import

### ISSUE THREAD

**Issue by dmr07** [firebase/firebase-functions#314]
### Version info

**firebase-functions:** 2.0.3

**firebase-tools:** 4.2.1

**firebase-admin:** 6.0.0

### Steps to reproduce

My app is a react app configured for SSR. 

`firebase deploy` on the following file: 

firebase.json
```
"functions": {
    "predeploy": [
      "npm --prefix \"$RESOURCE_DIR\" run lint"
    ],
    "source": "src/server"
  }
```
src/server/index.js
```
import functions from "firebase-functions";
import express from "express";
import cors from "cors";
import React from "react";
import {renderToString} from "react-dom/server";
import {StaticRouter, matchPath} from "react-router-dom";
import routes from "../shared/routes";
import App from "../shared/App";
import favicon from "serve-favicon";
import Html from "../client/Html";
import {Helmet} from "react-helmet";
import sourceMapSupport from "source-map-support";

const env = (process.env.NODE_ENV === "development") ? "dev" : "prod";
if (env === "dev") {
  sourceMapSupport.install();
}

const app = express();
const helmet = Helmet.renderStatic();

app.use(cors())
app.use(express.static("dist"))

// using __dirname doesn't work.
app.use(favicon("src/client/media/favicon.ico"))

app.get("*", (req, res, next) => {
  const activeRoute = routes.find(route => matchPath(req.url, route))
  const promise = activeRoute.fetchInitialData
    ? activeRoute.requestInitialData(req.path)
    : Promise.resolve()

  promise.then(initialData => {
    const context = { initialData }
    const markup = renderToString(
      <StaticRouter location={req.url} context={context}>
        <App />
      </StaticRouter>);
    if (env === "prod") {
      res.set('Cache-Control', 'public, max-age=3600') // 1hr 
    }
    return res.send(Html(markup, initialData))
  }).catch(next)
})

exports.app = functions.https.onRequest(app);
```

### Were you able to successfully deploy your functions?

No

### Expected behavior

Deployment on hosted site

### Actual behavior

console output:
```
Error: Error occurred while parsing your function triggers.

/Users/Dan/Projects/myproj/website/src/server/index.js:1
(function (exports, require, module, __filename, __dirname) { import functions from "firebase-functions";
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /usr/local/lib/node_modules/firebase-tools/lib/triggerParser.js:21:11
    at Object.<anonymous> (/usr/local/lib/node_modules/firebase-tools/lib/triggerParser.js:75:3)

Having trouble? Try firebase deploy --help
```

firebase-debug.log
```
[debug] [2018-09-01T17:55:08.885Z] ----------------------------------------------------------------------
[debug] [2018-09-01T17:55:08.887Z] Command:       /usr/local/bin/node /usr/local/bin/firebase deploy
[debug] [2018-09-01T17:55:08.887Z] CLI Version:   4.2.1
[debug] [2018-09-01T17:55:08.887Z] Platform:      darwin
[debug] [2018-09-01T17:55:08.888Z] Node Version:  v7.4.0
[debug] [2018-09-01T17:55:08.888Z] Time:          Sat Sep 01 2018 10:55:08 GMT-0700 (PDT)
[debug] [2018-09-01T17:55:08.888Z] ----------------------------------------------------------------------
[debug] 
[debug] [2018-09-01T17:55:08.899Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2018-09-01T17:55:08.900Z] > authorizing via signed-in user
[debug] [2018-09-01T17:55:08.902Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/projects/myproj 
 
[debug] [2018-09-01T17:55:09.540Z] <<< HTTP RESPONSE 200
[info] 
[info] === Deploying to '<intentionally removed>'...
[info] 
[info] i  deploying functions, hosting
[info] Running command: npm --prefix "$RESOURCE_DIR" run lint
[info] ✔  functions: Finished running predeploy script.
[debug] [2018-09-01T17:55:12.686Z] > [functions] package.json contents: {
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "scripts": {
    "lint": "eslint .",
    "serve": "firebase serve --only functions",
    "shell": "firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "dependencies": {
    "firebase-admin": "~6.0.0",
    "firebase-functions": "^2.0.5"
  },
  "devDependencies": {
    "eslint": "^4.12.0",
    "eslint-plugin-promise": "^3.6.0",
    "eslint-plugin-react": "^7.11.1"
  },
  "private": true
}
[info] i  functions: ensuring necessary APIs are enabled...
[debug] [2018-09-01T17:55:12.687Z] >>> HTTP REQUEST GET https://servicemanagement.googleapis.com/v1/services/cloudfunctions.googleapis.com/projectSettings/myproj?view=CONSUMER_VIEW  
 
[debug] [2018-09-01T17:55:12.688Z] >>> HTTP REQUEST GET https://servicemanagement.googleapis.com/v1/services/runtimeconfig.googleapis.com/projectSettings/myproj?view=CONSUMER_VIEW  
 
[debug] [2018-09-01T17:55:14.504Z] <<< HTTP RESPONSE 200

```

**Comment by Crazometer** [comment]
There is no native support in stable versions of node for`import`. You need to swap to `require` or use typescript/babel instead.

**Comment by thechenky** [comment]
@Crazometer is correct. It also looks like you have a predeploy hook for typescript (lint) but are actually using javascript. Closing this out.
