### ISSUE TITLE
Error 14: The service is temporarily unavailable.

### ISSUE THREAD

**Issue by zanecidan** [firebase/firebase-functions#345]
My Firebase Function is getting this error once in a while in production.
Error 14: The service is temporarily unavailable.

According to the Firebase console analytic I had roughly 400,000 invocations in last 7 days and 73 of this 'error 14' triggered. What is the cause of this error? Is there any way to fix this?

The full error log is as below:
Error: Error 14: The service is temporarily unavailable.
    at DestroyableTransform.stream.on.proto (/user_code/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/watch.js:576:33)
    at emitOne (events.js:96:13)
    at DestroyableTransform.emit (events.js:188:7)
    at addChunk (/user_code/node_modules/firebase-admin/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:291:12)
    at readableAddChunk (/user_code/node_modules/firebase-admin/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:278:11)
    at DestroyableTransform.Readable.push (/user_code/node_modules/firebase-admin/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:245:10)
    at DestroyableTransform.Transform.push (/user_code/node_modules/firebase-admin/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:148:32)
    at DestroyableTransform.afterTransform (/user_code/node_modules/firebase-admin/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:91:10)
    at DestroyableTransform.noop [as _transform] (/user_code/node_modules/firebase-admin/node_modules/through2/through2.js:26:3)
    at DestroyableTransform.Transform._read (/user_code/node_modules/firebase-admin/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/user_code/node_modules/firebase-admin/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/user_code/node_modules/firebase-admin/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:428:64)

**Comment by thechenky** [comment]
@zanecidan can you provide more info on which triggers you are using, and paste the relevant parts of your code? From looking at the numbers, 73 out of 400,000 is still a low percentage of error, can you give more context on what issues this is causing you?

**Comment by zanecidan** [comment]
@thechenky  ya thankfully the percentage of error is extremely low but it still affected some of our users. The cloud function is just a simple post API like below

`exports.functionName = functions.https.onRequest((req, res) => {
    
    const apiKey = req.header('apiKey');
    if(apiKey != constant.apiKey) res.send(400);
    if(req == null) res.send(400);
    
    // Function logic here

     res.send({
         'status': 200,
         'result': result
     });
});`

**Comment by thechenky** [comment]
Thanks for that update, @zanecidan. I would suggest adding some logic into your code to make it more resilient to these rare failures - perhaps a retry of some sort? Just like in any system, we cannot guarantee 100% reliability, so making your code handle these errors when they come up would be the best solution here.

**Comment by thechenky** [comment]
@zanecidan since there's been no activity here in some time, going to close this out. Please feel free to open another issue if you feel this needs more discussion, but I feel adding retries and making your code resilient would be the best course of action here.

**Comment by alfredolucomav** [comment]
Hi everyone,

I have two firebase project but only one of them hace that issue. What could be happen?
