### ISSUE TITLE
Error while deploying react based SSR app, using firebase-functions

### ISSUE THREAD

**Issue by subhendukundu** [firebase/firebase-functions#391]
I am trying to deploy my ssr app originally forked from https://github.com/subhendukundu/template-react-ssr/tree/feature/react-router, after doing some modification in the app.
Which works fine when I do ```sudo firebase serve --only functions,hosting``` but throwing error when I do ```firebase deploy```.
### [REQUIRED] Version info

2.1.0

**node:**
v8.11.3

**firebase-functions:**

**firebase-tools:**
v6.0.0

**firebase-admin:**
6.0.0

### [REQUIRED] Test case

https://github.com/subhendukundu/template-react-ssr/tree/feature/react-router

### [REQUIRED] Steps to reproduce

firebase deploy

### [REQUIRED] Expected behavior
It should deploy.

### [REQUIRED] Actual behavior

Function failed on loading user code. Error message: Code in file index.js can't be loaded.
Did you list all required modules in the package.json dependencies?
Detailed stack trace: Error: Cannot find module 'prop-types'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/user_code/assets/app.server.js:1:118293)
    at n (/user_code/assets/app.server.js:1:186)
    at Object.<anonymous> (/user_code/assets/app.server.js:1:117210)
    at n (/user_code/assets/app.server.js:1:186)
    at Object.module.exports.Object.defineProperty.value (/user_code/assets/app.server.js:1:118507)
    at n (/user_code/assets/app.server.js:1:186)
    at Object.<anonymous> (/user_code/assets/app.server.js:9:24696)
    at n (/user_code/assets/app.server.js:1:186)
    at Object.<anonymous> (/user_code/assets/app.server.js:1:122258)
    at n (/user_code/assets/app.server.js:1:186)
    at /user_code/assets/app.server.js:1:1083
    at Object.<anonymous> (/user_code/assets/app.server.js:1:1094)

### Were you able to successfully deploy your functions?

Function failed on loading user code. Error message: Code in file index.js can't be loaded.
Did you list all required modules in the package.json dependencies?
Detailed stack trace: Error: Cannot find module 'prop-types'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/user_code/assets/app.server.js:1:118293)
    at n (/user_code/assets/app.server.js:1:186)
    at Object.<anonymous> (/user_code/assets/app.server.js:1:117210)
    at n (/user_code/assets/app.server.js:1:186)
    at Object.module.exports.Object.defineProperty.value (/user_code/assets/app.server.js:1:118507)
    at n (/user_code/assets/app.server.js:1:186)
    at Object.<anonymous> (/user_code/assets/app.server.js:9:24696)
    at n (/user_code/assets/app.server.js:1:186)
    at Object.<anonymous> (/user_code/assets/app.server.js:1:122258)
    at n (/user_code/assets/app.server.js:1:186)
    at /user_code/assets/app.server.js:1:1083
    at Object.<anonymous> (/user_code/assets/app.server.js:1:1094)

**Comment by thechenky** [comment]
Hi @subhendukundu you are missing a `package.json` file inside your functions directory, which is causing this error. You can reference the following documentation to make sure you're configuring your functions correctly: https://firebase.google.com/docs/hosting/functions. Let me know if that helps.

**Comment by subhendukundu** [comment]
Hey @thechenky, sorry for the confusion, the reproducible repo is under the test case link in the description, which has a package.json https://github.com/subhendukundu/template-react-ssr/tree/feature/react-router/public
I am using the public directory as my function directory as well, https://github.com/subhendukundu/template-react-ssr/blob/feature/react-router/firebase.json
However even if I am using a different function directory for my cloud functions I see the same errors.
