### ISSUE TITLE
firebase-functions 2.3.1 transitively depends on @grpc/grpc-js 0.4.1 which is restricted to >= Node 8.13.0

### ISSUE THREAD

**Issue by opyate** [firebase/firebase-functions#454]
I've upgraded to firebase-functions 2.3.1 to get London region for functions. However, the version of `@grpc/grpc-js` it transitively depends on requires >= Node 8.13.0, which is not the same as the official cloud functions Node version 8.11.1

### [REQUIRED] Version info

**node:** 8.11.1 (same as cloud functions)

**firebase-functions:** 2.3.1

**firebase-tools:** 6.10.0

**firebase-admin:** 8.0.0

### [REQUIRED] Test case

Since I'm encountering this when using Firestore, use any official Firestore sample, e.g.:
https://github.com/firebase/functions-samples/blob/master/presence-firestore/functions/index.js

I suspect anything that uses gRPC under the hood will show the issue.

### [REQUIRED] Steps to reproduce

Query Firestore.

### [REQUIRED] Expected behavior

Result is returned.

### [REQUIRED] Actual behavior

```
(node:72678) ExperimentalWarning: The http2 module is an experimental API.
(node:72678) UnhandledPromiseRejectionWarning: Error: @grpc/grpc-js only works on Node ^8.13.0 || >=10.10.0
    at Object.<anonymous> (/code/functions/node_modules/@grpc/grpc-js/build/src/index.js:45:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/code/functions/node_modules/google-gax/build/src/grpc.js:37:14)
    at Module._compile (module.js:652:30)
```

### Were you able to successfully deploy your functions?

Functions deploy successfully.

**Comment by opyate** [comment]
I didn't get the memo: cloud functions are now v8.15.0
https://cloud.google.com/functions/docs/concepts/nodejs-8-runtime
