### ISSUE TITLE
Code 13 error on wake

### ISSUE THREAD

**Issue by henrylearn2rock** [firebase/firebase-functions#522]
```
{ Error
    at Http2CallStream.call.on (/srv/node_modules/@grpc/grpc-js/build/src/client.js:101:45)
    at emitOne (events.js:121:20)
    at Http2CallStream.emit (events.js:211:7)
    at process.nextTick (/srv/node_modules/@grpc/grpc-js/build/src/call-stream.js:71:22)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
  code: 13,
  details: '',
  metadata: Metadata { options: undefined, internalRepr: Map {} },
  note: 'Exception occurred in retry method that was not classified as transient' }
```

Functions v3.1.0 on Node 8

**Comment by thechenky** [comment]
@henrylearn2rock Please follow the template and fill out all required fields. This is not enough information to understand how to help.

**Comment by agcty** [comment]
I got the same issue, I'm uploading images with the firebase sdk for web clients. I assign custom metadata so that images can be matched to a specific document in firestore.
```javascript
let metaData = {
        customMetadata: {
          restaurantId: payload.restaurantId,
          dishId: dishId
        }
      };

```

The weird thing is that this happens approximately once out of 4 uploads with no clear sign why it does't work sometimes.
