### ISSUE TITLE
Error on .update() method.

### ISSUE THREAD

**Issue by h-ARTS** [firebase/firebase-functions#555]
### [REQUIRED] Version info

```
"engines": {
    "node": "8"
  },
  "dependencies": {
    "busboy": "^0.3.1",
    "firebase": "^6.6.0",
    "firebase-admin": "^8.5.0",
    "firebase-functions": "^3.2.0"
  },
  "devDependencies": {
    "firebase-functions-test": "^0.1.6"
  },
```

### [REQUIRED] Steps to reproduce

1. Create a new project with Cloud Firestore Database
2. Add a new collection. In my case 'users'
3. Add a new document e.g 'John'
4. Add any new fields e.g:
```
handle: John
website: http://www.john.com
email: john.doe@john.com
```
5. Initialize new firebase project with the firebase CLI and enter a similar code like this in index.js. The purpose of the code is to make an endpoint for updating document fields:
```
const functions = require('firebase-functions');
const admin = require('firebase-admin');

admin.initializeApp();

const db = admin.firestore();
const app = require('express')();

app.post('/user', (req, res) => {
  // Assume you validated the data in req.body 

  let userHandleRef = db.doc(`/users/${req.user.handle}`);
  userHandleRef.update(req.body)  // <-- Here we use the .update method
    .then(() => {
      return res.json({message: 'Details added successfully.'})
    })
    .catch(err => {
      console.error(err);
      return res.status(500).json({error: err.code});
    })
});

exports.api = functions.https.onRequest(app);
```
6. You can use Postman to try this endpoint: http://localhost:5000/(your-project)/us-central1/api/user and add the following JSON to the body as a POST request:
```
{
  "email": "doe.john@doe.com"
}
```
Or anything similar. You need to update anything.

7. Run the request

### [REQUIRED] Expected behavior

It should update the value of the field, in this case, the email and return:
```
{ message: 'Details added successfully.' }
```

### [REQUIRED] Actual behavior

Error log:
```
error: { Error: No document to update: projects/socialpage-3883d/databases/(default)/documents/users/Paki
    at Http2CallStream.call.on (/Users/hananmufti/Desktop/Projects/REACT_APPS/socialapp-functions/functions/node_modules/@grpc/grpc-js/build/src/client.js:96:45)
    at Http2CallStream.emit (events.js:187:15)
    at process.nextTick (/Users/hananmufti/Desktop/Projects/REACT_APPS/socialapp-functions/functions/node_modules/@grpc/grpc-js/build/src/call-stream.js:71:22)
    at process._tickCallback (internal/process/next_tick.js:61:11)
  code: 5,
  details:
   'No document to update: projects/socialpage-3883d/databases/(default)/documents/users/Paki',
  metadata: Metadata { options: undefined, internalRepr: Map {} } }
```

### Were you able to successfully deploy your functions?

I can successfully deploy my functions.

**Comment by schmidt-sebastian** [comment]
@h-ARTS Thanks for doing this and filing a new issue.

Can you change your code to the following:

```
Firestore.setLogFunction(console.log);

app.post('/user', async (req, res) => {
  // Assume you validated the data in req.body 

  let userHandleRef = db.doc(`/users/${req.user.handle}`);
  await db.doc(`/users/${req.user.handle}`).get();  // NEW
  userHandleRef.update(req.body);
    .then(() => {
      return res.json({message: 'Details added successfully.'})
    })
    .catch(err => {
      console.error(err);
      return res.status(500).json({error: err.code});
    })
});
```

When you run this, can you share your console output.

**Comment by h-ARTS** [comment]
@schmidt-sebastian 

```
info: Firestore (2.2.9) 2019-09-09T21:22:40.798Z ZEOBH [ClientPool.acquire]: Creating a new client
info: Firestore (2.2.9) 2019-09-09T21:22:41.076Z ##### [Firestore]: Initialized Firestore GAPIC Client
info: Firestore (2.2.9) 2019-09-09T21:22:41.080Z ZEOBH [Firestore.readStream]: Sending request: {"parent":"projects/socialpage-3883d/databases/(default)/documents","structuredQuery":{"from":[{"collectionId":"users"}],"where":{"fieldFilter":{"field":{"fieldPath":"userId"},"op":"EQUAL","value":{"stringValue":"kJKMrP9ZFhXPRjI2M4QNn98wxh63"}}},"limit":{"value":1}}}
info: Firestore (2.2.9) 2019-09-09T21:22:41.509Z ZEOBH [Firestore.readStream]: Received response: {"document":{"fields":{"createdAt":{"stringValue":"2019-09-08T11:30:32.039Z","valueType":"stringValue"},"handle":{"stringValue":"Paki","valueType":"stringValue"},"email":{"stringValue":"pak@hotmail.de","valueType":"stringValue"},"userId":{"stringValue":"kJKMrP9ZFhXPRjI2M4QNn98wxh63","valueType":"stringValue"},"imageUrl":{"stringValue":"https://firebasestorage.googleapis.com/v0/b/socialpage-3883d.appspot.com/o/avatar.png?alt=media","valueType":"stringValue"}},"name":"projects/socialpage-3883d/databases/(default)/documents/users/\u001cPaki","createTime":{"seconds":"1567942232","nanos":227496000},"updateTime":{"seconds":"1567942232","nanos":227496000}},"transaction":{"type":"Buffer","data":[]},"readTime":{"seconds":"1568064161","nanos":430219000},"skippedResults":0}
info: Firestore (2.2.9) 2019-09-09T21:22:41.509Z ZEOBH [Firestore._initializeStream]: Releasing stream
info: Firestore (2.2.9) 2019-09-09T21:22:41.515Z ZEOBH [Firestore._initializeStream]: Received stream end
info: DATA DOCS:  QueryDocumentSnapshot {
  _ref:
   DocumentReference {
     _firestore:
      Firestore {
        _settings: [Object],
        _settingsFrozen: true,
        _serializer: [Serializer],
        _projectId: 'socialpage-3883d',
        _lastSuccessfulRequest: 1568064161510,
        _preferTransactions: false,
        _clientPool: [ClientPool] },
     _path:
      QualifiedResourcePath {
        segments: [Array],
        projectId: 'socialpage-3883d',
        databaseId: '(default)' } },
  _fieldsProto:
   { createdAt:
      { stringValue: '2019-09-08T11:30:32.039Z',
        valueType: 'stringValue' },
     handle: { stringValue: 'Paki', valueType: 'stringValue' },
     email: { stringValue: 'pak@hotmail.de', valueType: 'stringValue' },
     userId:
      { stringValue: 'kJKMrP9ZFhXPRjI2M4QNn98wxh63',
        valueType: 'stringValue' },
     imageUrl:
      { stringValue:
         'https://firebasestorage.googleapis.com/v0/b/socialpage-3883d.appspot.com/o/avatar.png?alt=media',
        valueType: 'stringValue' } },
  _serializer:
   Serializer { createReference: [Function], timestampsInSnapshots: true },
  _readTime: Timestamp { _seconds: 1568064161, _nanoseconds: 430219000 },
  _createTime: Timestamp { _seconds: 1567942232, _nanoseconds: 227496000 },
  _updateTime: Timestamp { _seconds: 1567942232, _nanoseconds: 227496000 } }
info: Firestore (2.2.9) 2019-09-09T21:22:41.520Z Yi8PJ [ClientPool.acquire]: Re-using existing client with 100 remaining operations
info: Firestore (2.2.9) 2019-09-09T21:22:41.521Z Yi8PJ [Firestore.readStream]: Sending request: {"database":"projects/socialpage-3883d/databases/(default)","documents":["projects/socialpage-3883d/databases/(default)/documents/users/Paki"]}
info: Firestore (2.2.9) 2019-09-09T21:22:41.700Z Yi8PJ [Firestore.readStream]: Received response: {"transaction":{"type":"Buffer","data":[]},"readTime":{"seconds":"1568064161","nanos":632766000},"missing":"projects/socialpage-3883d/databases/(default)/documents/users/Paki","result":"missing"}
info: Firestore (2.2.9) 2019-09-09T21:22:41.701Z Yi8PJ [Firestore._initializeStream]: Releasing stream
info: Firestore (2.2.9) 2019-09-09T21:22:41.701Z Yi8PJ [Firestore.getAll_]: Document missing: projects/socialpage-3883d/databases/(default)/documents/users/Paki
info: Firestore (2.2.9) 2019-09-09T21:22:41.702Z Yi8PJ [Firestore._initializeStream]: Received stream end
info: Firestore (2.2.9) 2019-09-09T21:22:41.702Z Yi8PJ [Firestore.getAll_]: Received 1 results
info: Firestore (2.2.9) 2019-09-09T21:22:41.705Z I5nhb [WriteBatch.commit]: Sending 1 writes
info: Firestore (2.2.9) 2019-09-09T21:22:41.705Z I5nhb [ClientPool.acquire]: Re-using existing client with 100 remaining operations
info: Firestore (2.2.9) 2019-09-09T21:22:41.707Z I5nhb [Firestore.request]: Sending request: {"database":"projects/socialpage-3883d/databases/(default)","writes":[{"update":{"name":"projects/socialpage-3883d/databases/(default)/documents/users/Paki","fields":{"bio":{"stringValue":"my bio"}}},"updateMask":{"fieldPaths":["bio"]},"currentDocument":{"exists":true}}]}
info: Firestore (2.2.9) 2019-09-09T21:22:41.905Z I5nhb [Firestore.request]: Received error: { Error: No document to update: projects/socialpage-3883d/databases/(default)/documents/users/Paki
    at Http2CallStream.call.on (/Users/hananmufti/Desktop/Projects/REACT_APPS/socialapp-functions/functions/node_modules/@grpc/grpc-js/build/src/client.js:96:45)
    at Http2CallStream.emit (events.js:187:15)
    at process.nextTick (/Users/hananmufti/Desktop/Projects/REACT_APPS/socialapp-functions/functions/node_modules/@grpc/grpc-js/build/src/call-stream.js:71:22)
    at process._tickCallback (internal/process/next_tick.js:61:11)
  code: 5,
  details:
   'No document to update: projects/socialpage-3883d/databases/(default)/documents/users/Paki',
  metadata: Metadata { options: undefined, internalRepr: Map {} } }
info: Firestore (2.2.9) 2019-09-09T21:22:41.905Z I5nhb [Firestore._retry]: Request failed with unrecoverable error: { Error: No document to update: projects/socialpage-3883d/databases/(default)/documents/users/Paki
    at Http2CallStream.call.on (/Users/hananmufti/Desktop/Projects/REACT_APPS/socialapp-functions/functions/node_modules/@grpc/grpc-js/build/src/client.js:96:45)
    at Http2CallStream.emit (events.js:187:15)
    at process.nextTick (/Users/hananmufti/Desktop/Projects/REACT_APPS/socialapp-functions/functions/node_modules/@grpc/grpc-js/build/src/call-stream.js:71:22)
    at process._tickCallback (internal/process/next_tick.js:61:11)
  code: 5,
  details:
   'No document to update: projects/socialpage-3883d/databases/(default)/documents/users/Paki',
  metadata: Metadata { options: undefined, internalRepr: Map {} } }
error: { Error: No document to update: projects/socialpage-3883d/databases/(default)/documents/users/Paki
    at Http2CallStream.call.on (/Users/hananmufti/Desktop/Projects/REACT_APPS/socialapp-functions/functions/node_modules/@grpc/grpc-js/build/src/client.js:96:45)
    at Http2CallStream.emit (events.js:187:15)
    at process.nextTick (/Users/hananmufti/Desktop/Projects/REACT_APPS/socialapp-functions/functions/node_modules/@grpc/grpc-js/build/src/call-stream.js:71:22)
    at process._tickCallback (internal/process/next_tick.js:61:11)
  code: 5,
  details:
   'No document to update: projects/socialpage-3883d/databases/(default)/documents/users/Paki',
  metadata: Metadata { options: undefined, internalRepr: Map {} } }
info: Execution took 1351 ms, user function completed successfully
```

**Comment by schmidt-sebastian** [comment]
Thanks! The relevant bits are:

```
Sending request: {"database":"projects/socialpage-3883d/databases/(default)","documents":["projects/socialpage-3883d/databases/(default)/documents/users/Paki"]}
Received response: {"transaction":{"type":"Buffer","data":[]},"readTime":{"seconds":"1568064161","nanos":632766000},"missing":"projects/socialpage-3883d/databases/(default)/documents/users/Paki","result":"missing"}
Sending request: {"database":"projects/socialpage-3883d/databases/(default)","writes":[{"update":{"name":"projects/socialpage-3883d/databases/(default)/documents/users/Paki","fields":{"bio":{"stringValue":"my bio"}}},"updateMask":{"fieldPaths":["bio"]},"currentDocument":{"exists":true}}]}
Received error: { Error: No document to update: projects/socialpage-3883d/databases/(default)/documents/users/Paki
```

From this, it looks like /users/Paki does not exist. Can you confirm that this is indeed the document you believe to exist?

**Comment by h-ARTS** [comment]
@schmidt-sebastian I can confirm this again: 
<img width="1144" alt="Screenshot 2019-09-10 at 10 08 41" src="https://user-images.githubusercontent.com/11369764/64595863-1b2c3700-d3b3-11e9-9a7a-e04670dc1054.png">

**Comment by schmidt-sebastian** [comment]
@h-ARTS Are you sure your document name is actually "Paki"? From the UI it looks like there might be an empty space (it is not aligned with "Add document", whereas "Start collection" and "screams" are aligned).

**Comment by h-ARTS** [comment]
@schmidt-sebastian you are right there is an empty space in the beginning:
<img width="761" alt="Screenshot 2019-09-10 at 19 58 53" src="https://user-images.githubusercontent.com/11369764/64638288-c239be80-d405-11e9-9f38-b195fe4cabd7.png">

I investigated a bit further and I found that using template literal .doc() method without starting with the collection name like so '/users/..." places an empty space. I had to sort this out before but I think it's interesting to share:
````
db.doc(`${req.user.handle}`) -> /users/ Paki
```

**Comment by schmidt-sebastian** [comment]
Glad we figured this out!

I am little hesitant to believe that our string concatenation inserts spaces when using literals. This API has not changed since our initial release and we would be seeing issues like yours every day. With that said, I am closing this issue for now. If you do find an issue in our code, we can always re-open. 

Thank you!
