### ISSUE TITLE
[functions.config()] is EMPTY when running [firebase serve] or [firebase deploy]

### ISSUE THREAD

**Issue by super-jb** [firebase/firebase-functions#562]
### Related issues
I know some people have complained about this in the past but I can't seem to get this to work.

### [REQUIRED] Version info

**node:** v10.15.0

**firebase-functions:** ^3.0.0

**firebase-tools:**

**firebase:** 7.3.2

**firebase-admin:** ^8.0.0

### [REQUIRED] Test case
running **firebase serve** fails to read **functions.config()**

### [REQUIRED] Steps to reproduce

I've tried:
* firebase functions:config:get > .runtimeconfig.json (creates the .json file with me expected config values)
* firebase functions:config:get | ac .runtimeconfig.json (creates the .json with NO config values, just empty .json)
* I've tried putting the .runtimeconfig.json in the **functions** folder
* I've tried putting the .runtimeconfig.json in the **src** folder
* I've tried putting the .runtimeconfig.json in the **src** & the **functions** folder

### [REQUIRED] Expected behavior
Running **firebase serve** should read **functions.config()**

### [REQUIRED] Actual behavior
**functions.config()** seems to always be empty

This is the location that the code should read **functions.config()** values

 TypeError: Cannot read property 'secret' of undefined
    at Object.<anonymous> (C:\Development\stripe\functions\lib\config.js:13:49)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Development\stripe\functions\lib\source.js:5:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)

### Were you able to successfully deploy your functions?

No... running **firebase deploy --only functions gives me the exact same error.
If I replace **functions.config().myValue** with **the actual** value, both **firebase serve** and **firebase deploy** work

**Comment by Lucas-Geitner** [comment]
after few search, the issue is related here : 

https://github.com/firebase/firebase-functions/issues/264#issuecomment-398574364

**Comment by super-jb** [comment]
@Lucas-Geitner, I tried that approach (mentioned by @laurenzlong) and called it out in my initial comment, but the solution did not solve the problem.

* Running **firebase functions:config:get | ac .runtimeconfig.json** generates an **EMPTY** **runtimeconfig.json** file - this right here seems like a _red flag_
* Running **firebase functions:config:get > .runtimeconfig.json** generates a **runtimeconfig.json** file with the desired configurations present
* Executing both **firebase serve** and **firebase deploy** fail when the code reached the point of reading **functions.config().myValue**

**Comment by Lucas-Geitner** [comment]
Are you sure you need to use the serve method and not the shell command ?

**Comment by francisrod01** [comment]
@Lucas-Geitner I think you don't use environments in your firebase project.
But we use it all the time in cloud projects, that's why we need to put the envs in a place.

I have the same issue implementing my firebase functions project, and it's not possible to get any envs by code, but it's totally possible using the console:

```js
const config = {
  all: {
    env: process.env.NODE_ENV || firebaseEnv || 'development',
    root: path.join(__dirname, '..'),
    port: process.env.PORT || 9000,
    ip: process.env.IP || '0.0.0.0',
    defaultEmail: getFirebaseValue('emails.default'),
    sendgridKey: getFirebaseValue('sendgrid.key') || 'sendgridKey',
    masterKey: getFirebaseValue('master.key') || 'masterKey',
    jwtSecret: getFirebaseValue('jwt.secret') || 'jwtSecret',
    watsonKey: getFirebaseValue('watson.key'),
    facebook: {
      fbAppId: getFirebaseValue('facebook.app-id'),
      fbAppSecret: getFirebaseValue('facebook.app-secret'),
      authCallbackUrl: getFirebaseValue('facebook.auth-callback'),
    },
    unsplash: {
      applicationId: getFirebaseValue('unsplash.app-key'),
      secret: getFirebaseValue('unsplash.app-secret'),
      callbackUrl: getFirebaseValue('unsplash.callback-url'),
    },
    AWS: {
      accessKeyId: getFirebaseValue('aws.access-key'),
      secrectAccessKey: getFirebaseValue('aws.secret-access-key'),
      region: getFirebaseValue('aws.region'),
      bucket: getFirebaseValue('aws.bucket'),
    },
```

The method `getFirebaseValue()` is below:

```js
import _ from 'lodash';
const functions = require('firebase-functions');

const functionsEnvs = functions.config();

export const firebaseEnv = process.env.FIREBASE_CONFIG
  ? 'production'
  : 'development';

export const getFirebaseValue = envKey => {
  console.log(`[DEBUG] get the env ${envKey}: `, functionsEnvs[envKey]);
  console.log('[DEBUG] functions envs: ', JSON.stringify(functionsEnvs));
  return _.has(functionsEnvs, envKey)
    ? _.get(functionsEnvs, envKey)
    : undefined;
};
```

The answers I got here is below:

```bash
functions[webApi]: http function initialized (http://localhost:5000/social-api/us-central1/webApi).

i  functions: Beginning execution of "webApi"
>  [DEBUG] get the env emails.default:  undefined
>  [DEBUG] functions envs:  {}
>  [DEBUG] get the env sendgrid.key:  undefined
>  [DEBUG] functions envs:  {}
>  [DEBUG] get the env master.key:  undefined
>  [DEBUG] functions envs:  {}
>  [DEBUG] get the env jwt.secret:  undefined
>  [DEBUG] functions envs:  {}
>  [DEBUG] get the env watson.key:  undefined
>  [DEBUG] functions envs:  {}
>  [DEBUG] get the env facebook.app-id:  undefined
>  [DEBUG] functions envs:  {}
>  [DEBUG] get the env facebook.app-secret:  undefined
>  [DEBUG] functions envs:  {}
>  [DEBUG] get the env facebook.auth-callback:  undefined
>  [DEBUG] functions envs:  {}
>  [DEBUG] get the env unsplash.app-key:  undefined
>  [DEBUG] functions envs:  {}
>  [DEBUG] get the env unsplash.app-secret:  undefined
```

**Comment by francisrod01** [comment]
@Lucas-Geitner I think you don't use environments in your firebase project.
We use it all the time in cloud projects, that's why we need to put the envs in a place.

You can see that's the way Firebase had implemented that:
- [**Functions - Environment configuration:**](https://firebase.google.com/docs/functions/config-env)
- [**Functions - Access environment configuration in a function**](https://firebase.google.com/docs/functions/config-env#access_environment_configuration_in_a_function)

I'm going to explain it with a short code as a scenario using the @super-jb issue. 

I have the same issue implementing my firebase functions project, and it's not possible to get any envs by code, but it's totally possible using the console:

```js
const config = {
  all: {
    env: process.env.NODE_ENV || firebaseEnv || 'development',
    root: path.join(__dirname, '..'),
    port: process.env.PORT || 9000,
    ip: process.env.IP || '0.0.0.0',
    defaultEmail: getFirebaseValue('emails.default'),
    sendgridKey: getFirebaseValue('sendgrid.key') || 'sendgridKey',
    masterKey: getFirebaseValue('master.key') || 'masterKey',
    jwtSecret: getFirebaseValue('jwt.secret') || 'jwtSecret',
    watsonKey: getFirebaseValue('watson.key'),
    facebook: {
      fbAppId: getFirebaseValue('facebook.app-id'),
      fbAppSecret: getFirebaseValue('facebook.app-secret'),
      authCallbackUrl: getFirebaseValue('facebook.auth-callback'),
    },
    unsplash: {
      applicationId: getFirebaseValue('unsplash.app-key'),
      secret: getFirebaseValue('unsplash.app-secret'),
      callbackUrl: getFirebaseValue('unsplash.callback-url'),
    },
    AWS: {
      accessKeyId: getFirebaseValue('aws.access-key'),
      secrectAccessKey: getFirebaseValue('aws.secret-access-key'),
      region: getFirebaseValue('aws.region'),
      bucket: getFirebaseValue('aws.bucket'),
    },
```

The method `getFirebaseValue()` is below:

```js
import _ from 'lodash';
const functions = require('firebase-functions');

const functionsEnvs = functions.config();

export const firebaseEnv = process.env.FIREBASE_CONFIG
  ? 'production'
  : 'development';

export const getFirebaseValue = envKey => {
  console.log(`[DEBUG] get the env ${envKey}: `, _.get(functionsEnvs, envKey));
  return _.has(functionsEnvs, envKey)
    ? _.get(functionsEnvs, envKey)
    : undefined;
};
```

The answers I got here is below:

```bash
functions[webApi]: http function initialized (http://localhost:5000/social-api/us-central1/webApi).

i  functions: Beginning execution of "webApi"
>  [DEBUG] get the env emails.default:  undefined
>  [DEBUG] get the env sendgrid.key:  undefined
>  [DEBUG] get the env master.key:  undefined
>  [DEBUG] get the env jwt.secret:  undefined
>  [DEBUG] get the env watson.key:  undefined
>  [DEBUG] get the env facebook.app-id:  undefined
>  [DEBUG] get the env facebook.app-secret:  undefined
>  [DEBUG] get the env facebook.auth-callback:  undefined
>  [DEBUG] get the env unsplash.app-key:  undefined
>  [DEBUG] get the env unsplash.app-secret:  undefined
```

**Comment by samtstern** [comment]
Since this is an issue with `firebase serve` I am going to move this over to the firebase-tools repository.
