### ISSUE TITLE
Env Variables are ignored locally

### ISSUE THREAD

**Issue by SeanDez** [firebase/firebase-functions#591]
### Related issues
NA

### [REQUIRED] Version info

**node:** 12.4.0 (node 8 engine in package.json)

**firebase-functions:** 3.3.0

**firebase-tools:** 
firebase --version: 7.8.1

**firebase-admin:** 8.6.0

### [REQUIRED] Test case

```
// terminal
$ firebase functions:config:get
{
  "env": {
    "client_app_url": "https://us-central1-buyusedshopify.cloudfunctions.net/buyUsedServer"
  }
}

// index.ts
const { client_app_url } = process.env;

// below utility function is run inside of a route handler
const getRedirectUri = () => {
 console.log(client_app_url, `=====client_app_url=====`); 
 
 if (Boolean(client_app_url)) { return `${client_app_url}` }
 else {
  console.log(`=====Redirect URI is undefined=====`);
  throw Error("Redirect URI is undefined");
 }
};

// terminal output during firebase serve --only functions
  =====client_app_url=====
>  =====Redirect URI is undefined=====
>  Error: Redirect URI is undefined
>      at getRedirectUri (/home/owner/PhpstormProjects/shopify/buyUsedServer/functions/outDir/index.js:44:15)
>      at /home/owner/PhpstormProjects/shopify/buyUsedServer/functions/outDir/index.js:102:62
>      at Layer.handle [as handle_request] (/home/owner/PhpstormProjects/shopify/buyUsedServer/functions/node_modules/express/lib/router/layer.js:95:5)
>      at next (/home/owner/PhpstormProjects/shopify/buyUsedServer/functions/node_modules/express/lib/router/route.js:137:13)
>      at Route.dispatch (/home/owner/PhpstormProjects/shopify/buyUsedServer/functions/node_modules/express/lib/router/route.js:112:3)
>      at Layer.handle [as handle_request] (/home/owner/PhpstormProjects/shopify/buyUsedServer/functions/node_modules/express/lib/router/layer.js:95:5)
>      at /home/owner/PhpstormProjects/shopify/buyUsedServer/functions/node_modules/express/lib/router/index.js:281:22
>      at Function.process_params (/home/owner/PhpstormProjects/shopify/buyUsedServer/functions/node_modules/express/lib/router/index.js:335:12)
>      at next (/home/owner/PhpstormProjects/shopify/buyUsedServer/functions/node_modules/express/lib/router/index.js:275:10)
>      at expressInit (/home/owner/PhpstormProjects/shopify/buyUsedServer/functions/node_modules/express/lib/middleware/init.js:40:5)
i  functions: Finished "buyUsedServer" in ~1s


```

### [REQUIRED] Steps to reproduce

1. run in terminal: `firebase functions:config:set env.client_app_url="https://us-central1-buyusedshopify.cloudfunctions.net/buyUsedServer"`
2. run in terminal: `firebase serve`
3. setup a route handler for a GET method. Nest the utility function `getRedirectUri()` inside of it.
4. send a get request to url: `localhost:5000/buyusedshopify/us-central1/buyUsedServer/authorizationRequestor`
5. Error will appear in terminal

### [REQUIRED] Expected behavior

log statement in terminal with the interpolated env variable as part of the string.

### [REQUIRED] Actual behavior

This is an emulation specific error. I have copied it above in full.

### Were you able to successfully deploy your functions?

I can deploy but emulation is the issue here. The local Env variables are not loading correctly.

**Comment by SeanDez** [comment]
I see that the correct syntax to reference Env vars is this:

```
// replace process.env.keyname with:
functions.config().env.keyname
```

**Comment by SeanDez** [comment]
I am running into the following error now. What is the proper syntax to grab this? I'm using the emulator

```
const firebaseFunctions = require('firebase-functions');

firebaseAdmin.initializeApp({
 credential: firebaseAdmin.credential.applicationDefault(),
 databaseURL: 'https://removed.firebaseio.com'
});

// TypeError: Cannot destructure property `shopify_api_key` of 'undefined' or 'null'.
const {shopify_api_key, shopify_api_secret, scopes, client_app_url, GOOGLE_APPLICATION_CREDENTIALS } = firebaseFunctions.config().env;


```
