### ISSUE TITLE
fastify support

### ISSUE THREAD

**Issue by achmadk** [firebase/firebase-functions#609]
In [this video](https://www.youtube.com/watch?v=LOeioOKUKI8), firebase functions can successfully integrate with node.js application, specifically express framework. I want to use [fastify](https://www.fastify.io/benchmarks/) framework because it has better performance than express.

Unfortunately, when I am using fastify, I got error like this:
```js
TypeError: handler is not a function
    at cloudFunction (/srv/node_modules/firebase-functions/lib/providers/https.js:49:9)
    at /worker/worker.js:783:7
    at /worker/worker.js:766:11
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
```

**Comment by laurentpayot** [comment]
@achmadk If Fastify doesn't work for you there are other (an maybe better) options than Fastify to replace express: https://github.com/fastify/benchmarks#benchmarks

**Comment by taeold** [comment]
Check out fastify/fastify#946 for instructions on how to get fastify working for Firebase Functions.

It's a bit unfortunate that you have to jump through hoops to get things working. I'll see if there are ways to improve fastify integration w/ Firebase functions...

**Comment by shriekdj** [comment]
@achmadk  You should rename the issue to `TypeError: handler is not a function when deploying on fastify`
