### ISSUE TITLE
Can`t deploy function to southamerica-east1

### ISSUE THREAD

**Issue by tiagope** [firebase/firebase-functions#812]
### Related issues

Haven't seen any.

### [REQUIRED] Version info

**node:**  10.22.1

**firebase-functions:** 8.15.1

**firebase-tools:** 8.15.1

**firebase-admin:** 8.15.1

### [REQUIRED] Test case

```javascript
exports.api = functions.region('southamerica-east1')
                        .https.onRequest(app);
```

### [REQUIRED] Steps to reproduce

```bash
firebase deploy

i  functions: preparing functions directory for uploading...

Error: Error occurred while parsing your function triggers.

Error: The only valid regions are: us-central1, us-east1, us-east4, europe-west1, europe-west2, europe-west3, asia-east2, asia-northeast1
    at assertRegionsAreValid (C:\Projetos\retidos-functions\functions\node_modules\firebase-functions\lib\function-builder.js:62:15)
    at Object.region (C:\Projetos\retidos-functions\functions\node_modules\firebase-functions\lib\function-builder.js:75:9)    
    at Object.<anonymous> (C:\Projetos\retidos-functions\functions\index.js:36:25)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
```

### [REQUIRED] Expected behavior

Deploy function in southamerica-east1 region.
[Cloud Function Locations](https://cloud.google.com/functions/docs/locations)

### [REQUIRED] Actual behavior

Deployment issue. See **Steps to reproduce**

### Were you able to successfully deploy your functions?

Yes, in this regions:

```
us-central1, us-east1, us-east4, europe-west1, europe-west2, europe-west3, asia-east2, asia-northeast1
```

**Comment by samtstern** [comment]
@tiagope thanks for this feedback!  Sounds like we need to add support for this region.

**Comment by joehan** [comment]
Hey @tiagope, could you check which version of firebase-functions you are using, and try updating to the latest version? Support for `southamerica-east1` was added in version 3.8.0 https://github.com/firebase/firebase-functions/releases/tag/v3.8.0

**Comment by tiagope** [comment]
@joehan yes!

Everything is fine now!

Thanks!

**Comment by joehan** [comment]
Glad to hear! Closing this now :)
