### ISSUE TITLE
ERR_PACKAGE_PATH_NOT_EXPORTED (./lib/*)

### ISSUE THREAD

**Issue by pduchnovsky** [firebase/firebase-functions#946]
### [REQUIRED] Version info

**node:** 12.20.1

**firebase-functions:** 3.14.1

**firebase-tools:** 9.16.3

**firebase-admin:**

### [REQUIRED] Test case/Steps to reproduce

Use `import {ObjectMetadata} from 'firebase-functions/lib/providers/storage'` in your function
Using bitbucket pipelines with image: node:12.20.1
As part of the deploy pipeline script run:
`firebase deploy --only $functionslist --project $gcproject`

### [REQUIRED] Expected behavior

Successful import of lib/providers/storage, deployed functions

### [REQUIRED] Actual behavior

```
i  deploying functions
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
✔  functions: required API cloudbuild.googleapis.com is enabled
✔  functions: required API cloudfunctions.googleapis.com is enabled
Error: Error occurred while parsing your function triggers.
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/providers/storage' is not defined by "exports" in /opt/atlassian/pipelines/agent/build/lib/functions/node_modules/firebase-functions/package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:285:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:508:3)
    at resolveExports (internal/modules/cjs/loader.js:424:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:464:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:802:27)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/atlassian/pipelines/agent/build/lib/functions/firebase/firebaseHandlerFactory.js:2:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/atlassian/pipelines/agent/build/lib/functions/firebase/index.js:11:31)
```

### Were you able to successfully deploy your functions?

Not using current version, when downgraded firebase-functions @ 3.14. deploy worked.

**Comment by pduchnovsky** [comment]
error on our end.. we were importing `var _storage = require("firebase-functions/lib/providers/storage");` which seems removed in newest version.

**Comment by markgoho** [comment]
still happening in 3.15.3
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/encoder' is not defined by "exports" in ...\functions\node_modules\firebase-functions\package.json
```

**Comment by mbleigh** [comment]
@markgoho are you directly requiring that file, and what is your use case?

**Comment by markgoho** [comment]
@mbleigh I've changed nothing, just updating to 3.15.3 breaks my tests with the above error message. I have no idea what `./lib/encoder` is

**Comment by RuiChen0101** [comment]
@mbleigh same [ERR_PACKAGE_PATH_NOT_EXPORTED] error throw when upgrade to firebase-function@3.15.3. Complaining 'Package subpath './lib/encoder' is not defined by "exports"'

**Comment by AgungLaksana** [comment]
I upgrade firebase-functions from 3.14.1 to 3.15.3. and also @firebase/rules-unit-testing from 1.3.11 to 1.3.14. and when I want to perform unit testing using Firebase emulator I have the same error 

> Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/encoder' is not defined by "exports" in /Users/myPath/functions/node_modules/firebase-functions/package.json

**Comment by chuboyu** [comment]
Same issue here with @AgungLaksana. I am using firebase-functions-test 0.2.3.

`Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/encoder' is not defined by "exports" in`

After modifying the exports in package.json in node_modules/firebase-functions (adding './lib/encoder') seems to fix the issue.

The error seems to occur when firebase-functions-test tries to import  "firebase-functions/lib/encoder" in providers/firestore

**Comment by markgoho** [comment]
still happening in 3.15.4

``` bash
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/encoder' is not defined by "exports" in D:\IdeaCrew\active-branch-tracker\functions\node_modules\firebase-functions\package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:290:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:513:3)
    at resolveExports (internal/modules/cjs/loader.js:432:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:472:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (D:\IdeaCrew\active-branch-tracker\functions\node_modules\firebase-functions-test\lib\providers\firestore.js:26:19)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (D:\IdeaCrew\active-branch-tracker\functions\node_modules\firebase-functions-test\lib\features.js:8:19)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at module.exports (D:\IdeaCrew\active-branch-tracker\functions\node_modules\firebase-functions-test\lib\index.js:30:20)
    at Object.<anonymous> (D:\IdeaCrew\active-branch-tracker\functions\test\functions\branchDeployment.spec.ts:7:48)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module.m._compile (D:\IdeaCrew\active-branch-tracker\functions\node_modules\ts-node\src\index.ts:1043:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .ts] (D:\IdeaCrew\active-branch-tracker\functions\node_modules\ts-node\src\index.ts:1046:12)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.exports.requireOrImport (D:\IdeaCrew\active-branch-tracker\functions\node_modules\mocha\lib\esm-utils.js:56:20)
    at Object.exports.loadFilesAsync (D:\IdeaCrew\active-branch-tracker\functions\node_modules\mocha\lib\esm-utils.js:88:20)
    at singleRun (D:\IdeaCrew\active-branch-tracker\functions\node_modules\mocha\lib\cli\run-helpers.js:125:3)
    at Object.exports.handler (D:\IdeaCrew\active-branch-tracker\functions\node_modules\mocha\lib\cli\run.js:366:5)
```

**Comment by markgoho** [comment]
I was still experiencing this with firebase-functions `3.15.4` but then realized I was on firebase-functions-test `0.3.0` - after upgrading this package to `0.3.2` I no longer experience this missing export bug

**Comment by inlined** [comment]
The dependency on `lib/encoder` has been removed in yesterday's release of `firebase-functions-test`

**Comment by mandalornl** [comment]
@inlined I'm still having this issue using the emulator suite and `firebase-functions@3.15.x`. Follow the instructions below to reproduce.

1. Create an empty project and install the `Firebase Tools`.

```bash
$ mkdir firebase-functions-test
$ cd firebase-functions-test
$ yarn add -D firebase-tools
```

2. After that, initalize the `Functions` wizard. For testing purpose I selected `Don't set up a default project` and defaulted everything else.

```bash
$ firebase init functions
```

3. Then simply add the code below to `functions/index.js`.

```javascript 
const { logger } = require('firebase-functions/lib');

logger.info('test');
```

4. And run the emulator.

```bash
$ cd functions
$ yarn serve --project test
```
This will result with the following error.

```bash
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib' is not defined by "exports" in /[path-to-project-root]/firebase-functions-test/functions/node_modules/firebase-functions/package.json
```

**Comment by markgoho** [comment]
@mandalornl what version of `firebase-functions-test` are you using?

have you tried `rm -rf node-modules`, deleting your `yarn-lock.json` file and running `yarn` again?

**Comment by mandalornl** [comment]
@markgoho In the steps to reproduce the error I'm using `firebase-functions@3.15.4` and emulators from `firebase-tools@9.16.5`. I'm not using `firebase-functions-test` at the moment.

**Comment by inlined** [comment]
`firebase-functions/lib` is not a documented export, has never been a documented export, and will never be a documented export. Try

```
import * as logger from 'firebase-functions/logger'
```

**Comment by mandalornl** [comment]
Ah yes. For our projects `firebase-functions/lib` worked with `<=3.14.1`, but the import stated below works as well with `3.15.x`.

```javascript
import { logger } from 'firebase-functions'
```

Thank you for your time.
